// Nstance <https://nstance.dev>
// Copyright The Nstance Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/agent.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentService_ReceiveKeyRequests_FullMethodName = "/nstance.v1.AgentService/ReceiveKeyRequests"
	AgentService_SubmitPublicKeys_FullMethodName   = "/nstance.v1.AgentService/SubmitPublicKeys"
	AgentService_SubmitHealthReport_FullMethodName = "/nstance.v1.AgentService/SubmitHealthReport"
	AgentService_ReceiveFiles_FullMethodName       = "/nstance.v1.AgentService/ReceiveFiles"
)

// AgentServiceClient is the client API for AgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentService provides authenticated API for Nstance Agents
type AgentServiceClient interface {
	// ReceiveKeyRequests provides a persistent stream of key generation requests from server to agent
	ReceiveKeyRequests(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[KeyGenerationRequest], error)
	// SubmitPublicKeys allows agents to submit public keys for certificate generation
	SubmitPublicKeys(ctx context.Context, in *PublicKeysRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// SubmitHealthReport allows agents to send periodic health reports via persistent stream
	SubmitHealthReport(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[HealthReportRequest, emptypb.Empty], error)
	// ReceiveFiles provides a persistent stream of files from server to agent (certificates, secrets, config updates)
	ReceiveFiles(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileTransfer], error)
}

type agentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentServiceClient(cc grpc.ClientConnInterface) AgentServiceClient {
	return &agentServiceClient{cc}
}

func (c *agentServiceClient) ReceiveKeyRequests(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[KeyGenerationRequest], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[0], AgentService_ReceiveKeyRequests_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, KeyGenerationRequest]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_ReceiveKeyRequestsClient = grpc.ServerStreamingClient[KeyGenerationRequest]

func (c *agentServiceClient) SubmitPublicKeys(ctx context.Context, in *PublicKeysRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AgentService_SubmitPublicKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServiceClient) SubmitHealthReport(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[HealthReportRequest, emptypb.Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[1], AgentService_SubmitHealthReport_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HealthReportRequest, emptypb.Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_SubmitHealthReportClient = grpc.ClientStreamingClient[HealthReportRequest, emptypb.Empty]

func (c *agentServiceClient) ReceiveFiles(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[FileTransfer], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentService_ServiceDesc.Streams[2], AgentService_ReceiveFiles_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, FileTransfer]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_ReceiveFilesClient = grpc.ServerStreamingClient[FileTransfer]

// AgentServiceServer is the server API for AgentService service.
// All implementations must embed UnimplementedAgentServiceServer
// for forward compatibility.
//
// AgentService provides authenticated API for Nstance Agents
type AgentServiceServer interface {
	// ReceiveKeyRequests provides a persistent stream of key generation requests from server to agent
	ReceiveKeyRequests(*emptypb.Empty, grpc.ServerStreamingServer[KeyGenerationRequest]) error
	// SubmitPublicKeys allows agents to submit public keys for certificate generation
	SubmitPublicKeys(context.Context, *PublicKeysRequest) (*emptypb.Empty, error)
	// SubmitHealthReport allows agents to send periodic health reports via persistent stream
	SubmitHealthReport(grpc.ClientStreamingServer[HealthReportRequest, emptypb.Empty]) error
	// ReceiveFiles provides a persistent stream of files from server to agent (certificates, secrets, config updates)
	ReceiveFiles(*emptypb.Empty, grpc.ServerStreamingServer[FileTransfer]) error
	mustEmbedUnimplementedAgentServiceServer()
}

// UnimplementedAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentServiceServer struct{}

func (UnimplementedAgentServiceServer) ReceiveKeyRequests(*emptypb.Empty, grpc.ServerStreamingServer[KeyGenerationRequest]) error {
	return status.Errorf(codes.Unimplemented, "method ReceiveKeyRequests not implemented")
}
func (UnimplementedAgentServiceServer) SubmitPublicKeys(context.Context, *PublicKeysRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitPublicKeys not implemented")
}
func (UnimplementedAgentServiceServer) SubmitHealthReport(grpc.ClientStreamingServer[HealthReportRequest, emptypb.Empty]) error {
	return status.Errorf(codes.Unimplemented, "method SubmitHealthReport not implemented")
}
func (UnimplementedAgentServiceServer) ReceiveFiles(*emptypb.Empty, grpc.ServerStreamingServer[FileTransfer]) error {
	return status.Errorf(codes.Unimplemented, "method ReceiveFiles not implemented")
}
func (UnimplementedAgentServiceServer) mustEmbedUnimplementedAgentServiceServer() {}
func (UnimplementedAgentServiceServer) testEmbeddedByValue()                      {}

// UnsafeAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServiceServer will
// result in compilation errors.
type UnsafeAgentServiceServer interface {
	mustEmbedUnimplementedAgentServiceServer()
}

func RegisterAgentServiceServer(s grpc.ServiceRegistrar, srv AgentServiceServer) {
	// If the following call pancis, it indicates UnimplementedAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentService_ServiceDesc, srv)
}

func _AgentService_ReceiveKeyRequests_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).ReceiveKeyRequests(m, &grpc.GenericServerStream[emptypb.Empty, KeyGenerationRequest]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_ReceiveKeyRequestsServer = grpc.ServerStreamingServer[KeyGenerationRequest]

func _AgentService_SubmitPublicKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublicKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServiceServer).SubmitPublicKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentService_SubmitPublicKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServiceServer).SubmitPublicKeys(ctx, req.(*PublicKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentService_SubmitHealthReport_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentServiceServer).SubmitHealthReport(&grpc.GenericServerStream[HealthReportRequest, emptypb.Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_SubmitHealthReportServer = grpc.ClientStreamingServer[HealthReportRequest, emptypb.Empty]

func _AgentService_ReceiveFiles_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServiceServer).ReceiveFiles(m, &grpc.GenericServerStream[emptypb.Empty, FileTransfer]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentService_ReceiveFilesServer = grpc.ServerStreamingServer[FileTransfer]

// AgentService_ServiceDesc is the grpc.ServiceDesc for AgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nstance.v1.AgentService",
	HandlerType: (*AgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitPublicKeys",
			Handler:    _AgentService_SubmitPublicKeys_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReceiveKeyRequests",
			Handler:       _AgentService_ReceiveKeyRequests_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubmitHealthReport",
			Handler:       _AgentService_SubmitHealthReport_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "ReceiveFiles",
			Handler:       _AgentService_ReceiveFiles_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/agent.proto",
}
