// Nstance <https://nstance.dev>
// Copyright The Nstance Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/agent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KeyGenerationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyNames      []string               `protobuf:"bytes,1,rep,name=key_names,json=keyNames,proto3" json:"key_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyGenerationRequest) Reset() {
	*x = KeyGenerationRequest{}
	mi := &file_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyGenerationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyGenerationRequest) ProtoMessage() {}

func (x *KeyGenerationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyGenerationRequest.ProtoReflect.Descriptor instead.
func (*KeyGenerationRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *KeyGenerationRequest) GetKeyNames() []string {
	if x != nil {
		return x.KeyNames
	}
	return nil
}

type PublicKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Keys          []*PublicKeySubmission `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicKeysRequest) Reset() {
	*x = PublicKeysRequest{}
	mi := &file_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKeysRequest) ProtoMessage() {}

func (x *PublicKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKeysRequest.ProtoReflect.Descriptor instead.
func (*PublicKeysRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *PublicKeysRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *PublicKeysRequest) GetKeys() []*PublicKeySubmission {
	if x != nil {
		return x.Keys
	}
	return nil
}

type PublicKeySubmission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`                               // e.g., "kubelet.server"
	PublicKeyPem  []byte                 `protobuf:"bytes,2,opt,name=public_key_pem,json=publicKeyPem,proto3" json:"public_key_pem,omitempty"` // PEM-encoded public key
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicKeySubmission) Reset() {
	*x = PublicKeySubmission{}
	mi := &file_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicKeySubmission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKeySubmission) ProtoMessage() {}

func (x *PublicKeySubmission) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKeySubmission.ProtoReflect.Descriptor instead.
func (*PublicKeySubmission) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *PublicKeySubmission) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *PublicKeySubmission) GetPublicKeyPem() []byte {
	if x != nil {
		return x.PublicKeyPem
	}
	return nil
}

type HealthReportRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Version           string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"` // Agent version
	InstanceId        string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Timestamp         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Count             int64                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`                                                                          // Health report sequence number
	Uptime            string                 `protobuf:"bytes,5,opt,name=uptime,proto3" json:"uptime,omitempty"`                                                                         // Uptime duration string
	Metrics           *Metrics               `protobuf:"bytes,6,opt,name=metrics,proto3" json:"metrics,omitempty"`                                                                       // Metrics observed for this report
	Files             map[string]*FileStatus `protobuf:"bytes,7,rep,name=files,proto3" json:"files,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // File status map
	TerminationNotice *TerminationNotice     `protobuf:"bytes,8,opt,name=termination_notice,json=terminationNotice,proto3" json:"termination_notice,omitempty"`                          // Optional termination notice for spot instances
	ConfigHash        string                 `protobuf:"bytes,9,opt,name=config_hash,json=configHash,proto3" json:"config_hash,omitempty"`                                               // Runtime config hash from /opt/nstance-agent/identity/config.hash
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HealthReportRequest) Reset() {
	*x = HealthReportRequest{}
	mi := &file_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthReportRequest) ProtoMessage() {}

func (x *HealthReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthReportRequest.ProtoReflect.Descriptor instead.
func (*HealthReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *HealthReportRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthReportRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *HealthReportRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *HealthReportRequest) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *HealthReportRequest) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

func (x *HealthReportRequest) GetMetrics() *Metrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *HealthReportRequest) GetFiles() map[string]*FileStatus {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *HealthReportRequest) GetTerminationNotice() *TerminationNotice {
	if x != nil {
		return x.TerminationNotice
	}
	return nil
}

func (x *HealthReportRequest) GetConfigHash() string {
	if x != nil {
		return x.ConfigHash
	}
	return ""
}

type Metrics struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	CpuUsage              *float64               `protobuf:"fixed64,1,opt,name=cpu_usage,json=cpuUsage,proto3,oneof" json:"cpu_usage,omitempty"`                // CPU usage percentage
	CpuCoreUsage          []float64              `protobuf:"fixed64,2,rep,packed,name=cpu_core_usage,json=cpuCoreUsage,proto3" json:"cpu_core_usage,omitempty"` // Per-core CPU usage percentages
	MemoryUsage           *float64               `protobuf:"fixed64,3,opt,name=memory_usage,json=memoryUsage,proto3,oneof" json:"memory_usage,omitempty"`       // Memory usage percentage
	NetworkInterface      *InterfaceMetrics      `protobuf:"bytes,4,opt,name=network_interface,json=networkInterface,proto3,oneof" json:"network_interface,omitempty"`
	NetworkInterfaceError *string                `protobuf:"bytes,5,opt,name=network_interface_error,json=networkInterfaceError,proto3,oneof" json:"network_interface_error,omitempty"`
	EbpfCounters          map[uint32]uint64      `protobuf:"bytes,6,rep,name=ebpf_counters,json=ebpfCounters,proto3" json:"ebpf_counters,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"` // Active TCP connections keyed by target port
	EbpfError             *string                `protobuf:"bytes,7,opt,name=ebpf_error,json=ebpfError,proto3,oneof" json:"ebpf_error,omitempty"`
	ConntrackCount        *uint64                `protobuf:"varint,8,opt,name=conntrack_count,json=conntrackCount,proto3,oneof" json:"conntrack_count,omitempty"`
	ConntrackMax          *uint64                `protobuf:"varint,9,opt,name=conntrack_max,json=conntrackMax,proto3,oneof" json:"conntrack_max,omitempty"`
	ConntrackError        *string                `protobuf:"bytes,10,opt,name=conntrack_error,json=conntrackError,proto3,oneof" json:"conntrack_error,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Metrics) Reset() {
	*x = Metrics{}
	mi := &file_proto_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metrics) ProtoMessage() {}

func (x *Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metrics.ProtoReflect.Descriptor instead.
func (*Metrics) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{4}
}

func (x *Metrics) GetCpuUsage() float64 {
	if x != nil && x.CpuUsage != nil {
		return *x.CpuUsage
	}
	return 0
}

func (x *Metrics) GetCpuCoreUsage() []float64 {
	if x != nil {
		return x.CpuCoreUsage
	}
	return nil
}

func (x *Metrics) GetMemoryUsage() float64 {
	if x != nil && x.MemoryUsage != nil {
		return *x.MemoryUsage
	}
	return 0
}

func (x *Metrics) GetNetworkInterface() *InterfaceMetrics {
	if x != nil {
		return x.NetworkInterface
	}
	return nil
}

func (x *Metrics) GetNetworkInterfaceError() string {
	if x != nil && x.NetworkInterfaceError != nil {
		return *x.NetworkInterfaceError
	}
	return ""
}

func (x *Metrics) GetEbpfCounters() map[uint32]uint64 {
	if x != nil {
		return x.EbpfCounters
	}
	return nil
}

func (x *Metrics) GetEbpfError() string {
	if x != nil && x.EbpfError != nil {
		return *x.EbpfError
	}
	return ""
}

func (x *Metrics) GetConntrackCount() uint64 {
	if x != nil && x.ConntrackCount != nil {
		return *x.ConntrackCount
	}
	return 0
}

func (x *Metrics) GetConntrackMax() uint64 {
	if x != nil && x.ConntrackMax != nil {
		return *x.ConntrackMax
	}
	return 0
}

func (x *Metrics) GetConntrackError() string {
	if x != nil && x.ConntrackError != nil {
		return *x.ConntrackError
	}
	return ""
}

type InterfaceMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InterfaceName string                 `protobuf:"bytes,1,opt,name=interface_name,json=interfaceName,proto3" json:"interface_name,omitempty"`
	RxBytes       uint64                 `protobuf:"varint,2,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`
	TxBytes       uint64                 `protobuf:"varint,3,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	RxPackets     uint64                 `protobuf:"varint,4,opt,name=rx_packets,json=rxPackets,proto3" json:"rx_packets,omitempty"`
	TxPackets     uint64                 `protobuf:"varint,5,opt,name=tx_packets,json=txPackets,proto3" json:"tx_packets,omitempty"`
	RxDrops       uint64                 `protobuf:"varint,6,opt,name=rx_drops,json=rxDrops,proto3" json:"rx_drops,omitempty"`
	TxDrops       uint64                 `protobuf:"varint,7,opt,name=tx_drops,json=txDrops,proto3" json:"tx_drops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterfaceMetrics) Reset() {
	*x = InterfaceMetrics{}
	mi := &file_proto_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceMetrics) ProtoMessage() {}

func (x *InterfaceMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceMetrics.ProtoReflect.Descriptor instead.
func (*InterfaceMetrics) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{5}
}

func (x *InterfaceMetrics) GetInterfaceName() string {
	if x != nil {
		return x.InterfaceName
	}
	return ""
}

func (x *InterfaceMetrics) GetRxBytes() uint64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

func (x *InterfaceMetrics) GetTxBytes() uint64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

func (x *InterfaceMetrics) GetRxPackets() uint64 {
	if x != nil {
		return x.RxPackets
	}
	return 0
}

func (x *InterfaceMetrics) GetTxPackets() uint64 {
	if x != nil {
		return x.TxPackets
	}
	return 0
}

func (x *InterfaceMetrics) GetRxDrops() uint64 {
	if x != nil {
		return x.RxDrops
	}
	return 0
}

func (x *InterfaceMetrics) GetTxDrops() uint64 {
	if x != nil {
		return x.TxDrops
	}
	return 0
}

type FileStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Status:
	//
	//	*FileStatus_LastModified
	//	*FileStatus_Error
	Status        isFileStatus_Status `protobuf_oneof:"status"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileStatus) Reset() {
	*x = FileStatus{}
	mi := &file_proto_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileStatus) ProtoMessage() {}

func (x *FileStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileStatus.ProtoReflect.Descriptor instead.
func (*FileStatus) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{6}
}

func (x *FileStatus) GetStatus() isFileStatus_Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *FileStatus) GetLastModified() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.Status.(*FileStatus_LastModified); ok {
			return x.LastModified
		}
	}
	return nil
}

func (x *FileStatus) GetError() string {
	if x != nil {
		if x, ok := x.Status.(*FileStatus_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isFileStatus_Status interface {
	isFileStatus_Status()
}

type FileStatus_LastModified struct {
	LastModified *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=last_modified,json=lastModified,proto3,oneof"` // File exists and last modified time
}

type FileStatus_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"` // Error accessing file
}

func (*FileStatus_LastModified) isFileStatus_Status() {}

func (*FileStatus_Error) isFileStatus_Status() {}

type TerminationNotice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`     // Action to take, e.g., "terminate"
	Deadline      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=deadline,proto3" json:"deadline,omitempty"` // Optional termination deadline
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminationNotice) Reset() {
	*x = TerminationNotice{}
	mi := &file_proto_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminationNotice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminationNotice) ProtoMessage() {}

func (x *TerminationNotice) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminationNotice.ProtoReflect.Descriptor instead.
func (*TerminationNotice) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{7}
}

func (x *TerminationNotice) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *TerminationNotice) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

type FileTransfer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	LastModified  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_modified,json=lastModified,proto3" json:"last_modified,omitempty"`
	ConfigHash    string                 `protobuf:"bytes,4,opt,name=config_hash,json=configHash,proto3" json:"config_hash,omitempty"` // Non-empty on a filename-free commit message; applies the patch and updates identity/config.hash
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileTransfer) Reset() {
	*x = FileTransfer{}
	mi := &file_proto_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileTransfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileTransfer) ProtoMessage() {}

func (x *FileTransfer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileTransfer.ProtoReflect.Descriptor instead.
func (*FileTransfer) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{8}
}

func (x *FileTransfer) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileTransfer) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *FileTransfer) GetLastModified() *timestamppb.Timestamp {
	if x != nil {
		return x.LastModified
	}
	return nil
}

func (x *FileTransfer) GetConfigHash() string {
	if x != nil {
		return x.ConfigHash
	}
	return ""
}

var File_proto_agent_proto protoreflect.FileDescriptor

const file_proto_agent_proto_rawDesc = "" +
	"\n" +
	"\x11proto/agent.proto\x12\n" +
	"nstance.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"3\n" +
	"\x14KeyGenerationRequest\x12\x1b\n" +
	"\tkey_names\x18\x01 \x03(\tR\bkeyNames\"i\n" +
	"\x11PublicKeysRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x123\n" +
	"\x04keys\x18\x02 \x03(\v2\x1f.nstance.v1.PublicKeySubmissionR\x04keys\"W\n" +
	"\x13PublicKeySubmission\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12$\n" +
	"\x0epublic_key_pem\x18\x02 \x01(\fR\fpublicKeyPem\"\xea\x03\n" +
	"\x13HealthReportRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x03R\x05count\x12\x16\n" +
	"\x06uptime\x18\x05 \x01(\tR\x06uptime\x12-\n" +
	"\ametrics\x18\x06 \x01(\v2\x13.nstance.v1.MetricsR\ametrics\x12@\n" +
	"\x05files\x18\a \x03(\v2*.nstance.v1.HealthReportRequest.FilesEntryR\x05files\x12L\n" +
	"\x12termination_notice\x18\b \x01(\v2\x1d.nstance.v1.TerminationNoticeR\x11terminationNotice\x12\x1f\n" +
	"\vconfig_hash\x18\t \x01(\tR\n" +
	"configHash\x1aP\n" +
	"\n" +
	"FilesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.nstance.v1.FileStatusR\x05value:\x028\x01\"\xd7\x05\n" +
	"\aMetrics\x12 \n" +
	"\tcpu_usage\x18\x01 \x01(\x01H\x00R\bcpuUsage\x88\x01\x01\x12$\n" +
	"\x0ecpu_core_usage\x18\x02 \x03(\x01R\fcpuCoreUsage\x12&\n" +
	"\fmemory_usage\x18\x03 \x01(\x01H\x01R\vmemoryUsage\x88\x01\x01\x12N\n" +
	"\x11network_interface\x18\x04 \x01(\v2\x1c.nstance.v1.InterfaceMetricsH\x02R\x10networkInterface\x88\x01\x01\x12;\n" +
	"\x17network_interface_error\x18\x05 \x01(\tH\x03R\x15networkInterfaceError\x88\x01\x01\x12J\n" +
	"\rebpf_counters\x18\x06 \x03(\v2%.nstance.v1.Metrics.EbpfCountersEntryR\febpfCounters\x12\"\n" +
	"\n" +
	"ebpf_error\x18\a \x01(\tH\x04R\tebpfError\x88\x01\x01\x12,\n" +
	"\x0fconntrack_count\x18\b \x01(\x04H\x05R\x0econntrackCount\x88\x01\x01\x12(\n" +
	"\rconntrack_max\x18\t \x01(\x04H\x06R\fconntrackMax\x88\x01\x01\x12,\n" +
	"\x0fconntrack_error\x18\n" +
	" \x01(\tH\aR\x0econntrackError\x88\x01\x01\x1a?\n" +
	"\x11EbpfCountersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01B\f\n" +
	"\n" +
	"_cpu_usageB\x0f\n" +
	"\r_memory_usageB\x14\n" +
	"\x12_network_interfaceB\x1a\n" +
	"\x18_network_interface_errorB\r\n" +
	"\v_ebpf_errorB\x12\n" +
	"\x10_conntrack_countB\x10\n" +
	"\x0e_conntrack_maxB\x12\n" +
	"\x10_conntrack_error\"\xe3\x01\n" +
	"\x10InterfaceMetrics\x12%\n" +
	"\x0einterface_name\x18\x01 \x01(\tR\rinterfaceName\x12\x19\n" +
	"\brx_bytes\x18\x02 \x01(\x04R\arxBytes\x12\x19\n" +
	"\btx_bytes\x18\x03 \x01(\x04R\atxBytes\x12\x1d\n" +
	"\n" +
	"rx_packets\x18\x04 \x01(\x04R\trxPackets\x12\x1d\n" +
	"\n" +
	"tx_packets\x18\x05 \x01(\x04R\ttxPackets\x12\x19\n" +
	"\brx_drops\x18\x06 \x01(\x04R\arxDrops\x12\x19\n" +
	"\btx_drops\x18\a \x01(\x04R\atxDrops\"q\n" +
	"\n" +
	"FileStatus\x12A\n" +
	"\rlast_modified\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\flastModified\x12\x16\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05errorB\b\n" +
	"\x06status\"c\n" +
	"\x11TerminationNotice\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x126\n" +
	"\bdeadline\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\"\xa6\x01\n" +
	"\fFileTransfer\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12?\n" +
	"\rlast_modified\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\flastModified\x12\x1f\n" +
	"\vconfig_hash\x18\x04 \x01(\tR\n" +
	"configHash2\xc0\x02\n" +
	"\fAgentService\x12P\n" +
	"\x12ReceiveKeyRequests\x12\x16.google.protobuf.Empty\x1a .nstance.v1.KeyGenerationRequest0\x01\x12I\n" +
	"\x10SubmitPublicKeys\x12\x1d.nstance.v1.PublicKeysRequest\x1a\x16.google.protobuf.Empty\x12O\n" +
	"\x12SubmitHealthReport\x12\x1f.nstance.v1.HealthReportRequest\x1a\x16.google.protobuf.Empty(\x01\x12B\n" +
	"\fReceiveFiles\x12\x16.google.protobuf.Empty\x1a\x18.nstance.v1.FileTransfer0\x01B/Z-github.com/nstance-dev/nstance/internal/protob\x06proto3"

var (
	file_proto_agent_proto_rawDescOnce sync.Once
	file_proto_agent_proto_rawDescData []byte
)

func file_proto_agent_proto_rawDescGZIP() []byte {
	file_proto_agent_proto_rawDescOnce.Do(func() {
		file_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)))
	})
	return file_proto_agent_proto_rawDescData
}

var file_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_agent_proto_goTypes = []any{
	(*KeyGenerationRequest)(nil),  // 0: nstance.v1.KeyGenerationRequest
	(*PublicKeysRequest)(nil),     // 1: nstance.v1.PublicKeysRequest
	(*PublicKeySubmission)(nil),   // 2: nstance.v1.PublicKeySubmission
	(*HealthReportRequest)(nil),   // 3: nstance.v1.HealthReportRequest
	(*Metrics)(nil),               // 4: nstance.v1.Metrics
	(*InterfaceMetrics)(nil),      // 5: nstance.v1.InterfaceMetrics
	(*FileStatus)(nil),            // 6: nstance.v1.FileStatus
	(*TerminationNotice)(nil),     // 7: nstance.v1.TerminationNotice
	(*FileTransfer)(nil),          // 8: nstance.v1.FileTransfer
	nil,                           // 9: nstance.v1.HealthReportRequest.FilesEntry
	nil,                           // 10: nstance.v1.Metrics.EbpfCountersEntry
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 12: google.protobuf.Empty
}
var file_proto_agent_proto_depIdxs = []int32{
	2,  // 0: nstance.v1.PublicKeysRequest.keys:type_name -> nstance.v1.PublicKeySubmission
	11, // 1: nstance.v1.HealthReportRequest.timestamp:type_name -> google.protobuf.Timestamp
	4,  // 2: nstance.v1.HealthReportRequest.metrics:type_name -> nstance.v1.Metrics
	9,  // 3: nstance.v1.HealthReportRequest.files:type_name -> nstance.v1.HealthReportRequest.FilesEntry
	7,  // 4: nstance.v1.HealthReportRequest.termination_notice:type_name -> nstance.v1.TerminationNotice
	5,  // 5: nstance.v1.Metrics.network_interface:type_name -> nstance.v1.InterfaceMetrics
	10, // 6: nstance.v1.Metrics.ebpf_counters:type_name -> nstance.v1.Metrics.EbpfCountersEntry
	11, // 7: nstance.v1.FileStatus.last_modified:type_name -> google.protobuf.Timestamp
	11, // 8: nstance.v1.TerminationNotice.deadline:type_name -> google.protobuf.Timestamp
	11, // 9: nstance.v1.FileTransfer.last_modified:type_name -> google.protobuf.Timestamp
	6,  // 10: nstance.v1.HealthReportRequest.FilesEntry.value:type_name -> nstance.v1.FileStatus
	12, // 11: nstance.v1.AgentService.ReceiveKeyRequests:input_type -> google.protobuf.Empty
	1,  // 12: nstance.v1.AgentService.SubmitPublicKeys:input_type -> nstance.v1.PublicKeysRequest
	3,  // 13: nstance.v1.AgentService.SubmitHealthReport:input_type -> nstance.v1.HealthReportRequest
	12, // 14: nstance.v1.AgentService.ReceiveFiles:input_type -> google.protobuf.Empty
	0,  // 15: nstance.v1.AgentService.ReceiveKeyRequests:output_type -> nstance.v1.KeyGenerationRequest
	12, // 16: nstance.v1.AgentService.SubmitPublicKeys:output_type -> google.protobuf.Empty
	12, // 17: nstance.v1.AgentService.SubmitHealthReport:output_type -> google.protobuf.Empty
	8,  // 18: nstance.v1.AgentService.ReceiveFiles:output_type -> nstance.v1.FileTransfer
	15, // [15:19] is the sub-list for method output_type
	11, // [11:15] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_agent_proto_init() }
func file_proto_agent_proto_init() {
	if File_proto_agent_proto != nil {
		return
	}
	file_proto_agent_proto_msgTypes[4].OneofWrappers = []any{}
	file_proto_agent_proto_msgTypes[6].OneofWrappers = []any{
		(*FileStatus_LastModified)(nil),
		(*FileStatus_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agent_proto_goTypes,
		DependencyIndexes: file_proto_agent_proto_depIdxs,
		MessageInfos:      file_proto_agent_proto_msgTypes,
	}.Build()
	File_proto_agent_proto = out.File
	file_proto_agent_proto_goTypes = nil
	file_proto_agent_proto_depIdxs = nil
}
