// Nstance <https://nstance.dev>
// Copyright 2026 Nadrama Pty Ltd
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: proto/agent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KeyGenerationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyNames      []string               `protobuf:"bytes,1,rep,name=key_names,json=keyNames,proto3" json:"key_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyGenerationRequest) Reset() {
	*x = KeyGenerationRequest{}
	mi := &file_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyGenerationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyGenerationRequest) ProtoMessage() {}

func (x *KeyGenerationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyGenerationRequest.ProtoReflect.Descriptor instead.
func (*KeyGenerationRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *KeyGenerationRequest) GetKeyNames() []string {
	if x != nil {
		return x.KeyNames
	}
	return nil
}

type PublicKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Keys          []*PublicKeySubmission `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicKeysRequest) Reset() {
	*x = PublicKeysRequest{}
	mi := &file_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKeysRequest) ProtoMessage() {}

func (x *PublicKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKeysRequest.ProtoReflect.Descriptor instead.
func (*PublicKeysRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *PublicKeysRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *PublicKeysRequest) GetKeys() []*PublicKeySubmission {
	if x != nil {
		return x.Keys
	}
	return nil
}

type PublicKeySubmission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`                               // e.g., "kubelet.server"
	PublicKeyPem  []byte                 `protobuf:"bytes,2,opt,name=public_key_pem,json=publicKeyPem,proto3" json:"public_key_pem,omitempty"` // PEM-encoded public key
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicKeySubmission) Reset() {
	*x = PublicKeySubmission{}
	mi := &file_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicKeySubmission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicKeySubmission) ProtoMessage() {}

func (x *PublicKeySubmission) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicKeySubmission.ProtoReflect.Descriptor instead.
func (*PublicKeySubmission) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *PublicKeySubmission) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *PublicKeySubmission) GetPublicKeyPem() []byte {
	if x != nil {
		return x.PublicKeyPem
	}
	return nil
}

type HealthReportRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Version           string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"` // Agent version
	InstanceId        string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Timestamp         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Count             int64                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`                                                                           // Health report sequence number
	Started           *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=started,proto3" json:"started,omitempty"`                                                                        // When metrics collection started
	WindowStart       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=window_start,json=windowStart,proto3" json:"window_start,omitempty"`                                             // Current metrics window start
	WindowEnd         *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=window_end,json=windowEnd,proto3" json:"window_end,omitempty"`                                                   // Current metrics window end
	Uptime            string                 `protobuf:"bytes,8,opt,name=uptime,proto3" json:"uptime,omitempty"`                                                                          // Uptime duration string
	OneMinute         *Metrics               `protobuf:"bytes,9,opt,name=one_minute,json=oneMinute,proto3" json:"one_minute,omitempty"`                                                   // 1-minute averages
	FiveMinutes       *Metrics               `protobuf:"bytes,10,opt,name=five_minutes,json=fiveMinutes,proto3" json:"five_minutes,omitempty"`                                            // 5-minute averages
	FifteenMinutes    *Metrics               `protobuf:"bytes,11,opt,name=fifteen_minutes,json=fifteenMinutes,proto3" json:"fifteen_minutes,omitempty"`                                   // 15-minute averages
	Files             map[string]*FileStatus `protobuf:"bytes,12,rep,name=files,proto3" json:"files,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // File status map
	TerminationNotice *TerminationNotice     `protobuf:"bytes,13,opt,name=termination_notice,json=terminationNotice,proto3" json:"termination_notice,omitempty"`                          // Optional termination notice for spot instances
	ConfigHash        string                 `protobuf:"bytes,14,opt,name=config_hash,json=configHash,proto3" json:"config_hash,omitempty"`                                               // Runtime config hash from /opt/nstance-agent/identity/config.hash
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HealthReportRequest) Reset() {
	*x = HealthReportRequest{}
	mi := &file_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthReportRequest) ProtoMessage() {}

func (x *HealthReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthReportRequest.ProtoReflect.Descriptor instead.
func (*HealthReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *HealthReportRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthReportRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *HealthReportRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *HealthReportRequest) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *HealthReportRequest) GetStarted() *timestamppb.Timestamp {
	if x != nil {
		return x.Started
	}
	return nil
}

func (x *HealthReportRequest) GetWindowStart() *timestamppb.Timestamp {
	if x != nil {
		return x.WindowStart
	}
	return nil
}

func (x *HealthReportRequest) GetWindowEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.WindowEnd
	}
	return nil
}

func (x *HealthReportRequest) GetUptime() string {
	if x != nil {
		return x.Uptime
	}
	return ""
}

func (x *HealthReportRequest) GetOneMinute() *Metrics {
	if x != nil {
		return x.OneMinute
	}
	return nil
}

func (x *HealthReportRequest) GetFiveMinutes() *Metrics {
	if x != nil {
		return x.FiveMinutes
	}
	return nil
}

func (x *HealthReportRequest) GetFifteenMinutes() *Metrics {
	if x != nil {
		return x.FifteenMinutes
	}
	return nil
}

func (x *HealthReportRequest) GetFiles() map[string]*FileStatus {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *HealthReportRequest) GetTerminationNotice() *TerminationNotice {
	if x != nil {
		return x.TerminationNotice
	}
	return nil
}

func (x *HealthReportRequest) GetConfigHash() string {
	if x != nil {
		return x.ConfigHash
	}
	return ""
}

type Metrics struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	CpuUsage             float64                `protobuf:"fixed64,1,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`                                       // CPU usage percentage
	CpuCoreUsage         []float64              `protobuf:"fixed64,2,rep,packed,name=cpu_core_usage,json=cpuCoreUsage,proto3" json:"cpu_core_usage,omitempty"`                  // Per-core CPU usage percentages
	MemoryUsage          float64                `protobuf:"fixed64,3,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`                              // Memory usage percentage
	NetworkBytesSent     float64                `protobuf:"fixed64,4,opt,name=network_bytes_sent,json=networkBytesSent,proto3" json:"network_bytes_sent,omitempty"`             // Network bytes sent
	NetworkBytesReceived float64                `protobuf:"fixed64,5,opt,name=network_bytes_received,json=networkBytesReceived,proto3" json:"network_bytes_received,omitempty"` // Network bytes received
	DiskUsed             float64                `protobuf:"fixed64,6,opt,name=disk_used,json=diskUsed,proto3" json:"disk_used,omitempty"`                                       // Disk usage percentage
	DiskInodesUsed       float64                `protobuf:"fixed64,7,opt,name=disk_inodes_used,json=diskInodesUsed,proto3" json:"disk_inodes_used,omitempty"`                   // Disk inode usage percentage
	DiskBytesRead        float64                `protobuf:"fixed64,8,opt,name=disk_bytes_read,json=diskBytesRead,proto3" json:"disk_bytes_read,omitempty"`                      // Disk bytes read
	DiskBytesWritten     float64                `protobuf:"fixed64,9,opt,name=disk_bytes_written,json=diskBytesWritten,proto3" json:"disk_bytes_written,omitempty"`             // Disk bytes written
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Metrics) Reset() {
	*x = Metrics{}
	mi := &file_proto_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metrics) ProtoMessage() {}

func (x *Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metrics.ProtoReflect.Descriptor instead.
func (*Metrics) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{4}
}

func (x *Metrics) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *Metrics) GetCpuCoreUsage() []float64 {
	if x != nil {
		return x.CpuCoreUsage
	}
	return nil
}

func (x *Metrics) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *Metrics) GetNetworkBytesSent() float64 {
	if x != nil {
		return x.NetworkBytesSent
	}
	return 0
}

func (x *Metrics) GetNetworkBytesReceived() float64 {
	if x != nil {
		return x.NetworkBytesReceived
	}
	return 0
}

func (x *Metrics) GetDiskUsed() float64 {
	if x != nil {
		return x.DiskUsed
	}
	return 0
}

func (x *Metrics) GetDiskInodesUsed() float64 {
	if x != nil {
		return x.DiskInodesUsed
	}
	return 0
}

func (x *Metrics) GetDiskBytesRead() float64 {
	if x != nil {
		return x.DiskBytesRead
	}
	return 0
}

func (x *Metrics) GetDiskBytesWritten() float64 {
	if x != nil {
		return x.DiskBytesWritten
	}
	return 0
}

type FileStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Status:
	//
	//	*FileStatus_LastModified
	//	*FileStatus_Error
	Status        isFileStatus_Status `protobuf_oneof:"status"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileStatus) Reset() {
	*x = FileStatus{}
	mi := &file_proto_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileStatus) ProtoMessage() {}

func (x *FileStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileStatus.ProtoReflect.Descriptor instead.
func (*FileStatus) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{5}
}

func (x *FileStatus) GetStatus() isFileStatus_Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *FileStatus) GetLastModified() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.Status.(*FileStatus_LastModified); ok {
			return x.LastModified
		}
	}
	return nil
}

func (x *FileStatus) GetError() string {
	if x != nil {
		if x, ok := x.Status.(*FileStatus_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isFileStatus_Status interface {
	isFileStatus_Status()
}

type FileStatus_LastModified struct {
	LastModified *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=last_modified,json=lastModified,proto3,oneof"` // File exists and last modified time
}

type FileStatus_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"` // Error accessing file
}

func (*FileStatus_LastModified) isFileStatus_Status() {}

func (*FileStatus_Error) isFileStatus_Status() {}

type TerminationNotice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        string                 `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`     // Action to take, e.g., "terminate"
	Deadline      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=deadline,proto3" json:"deadline,omitempty"` // Optional termination deadline
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminationNotice) Reset() {
	*x = TerminationNotice{}
	mi := &file_proto_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminationNotice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminationNotice) ProtoMessage() {}

func (x *TerminationNotice) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminationNotice.ProtoReflect.Descriptor instead.
func (*TerminationNotice) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{6}
}

func (x *TerminationNotice) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *TerminationNotice) GetDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.Deadline
	}
	return nil
}

type FileTransfer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	LastModified  *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=last_modified,json=lastModified,proto3" json:"last_modified,omitempty"`
	ConfigHash    string                 `protobuf:"bytes,4,opt,name=config_hash,json=configHash,proto3" json:"config_hash,omitempty"` // Optional: updated runtime config hash to write to identity/config.hash
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileTransfer) Reset() {
	*x = FileTransfer{}
	mi := &file_proto_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileTransfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileTransfer) ProtoMessage() {}

func (x *FileTransfer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileTransfer.ProtoReflect.Descriptor instead.
func (*FileTransfer) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{7}
}

func (x *FileTransfer) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileTransfer) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *FileTransfer) GetLastModified() *timestamppb.Timestamp {
	if x != nil {
		return x.LastModified
	}
	return nil
}

func (x *FileTransfer) GetConfigHash() string {
	if x != nil {
		return x.ConfigHash
	}
	return ""
}

var File_proto_agent_proto protoreflect.FileDescriptor

const file_proto_agent_proto_rawDesc = "" +
	"\n" +
	"\x11proto/agent.proto\x12\n" +
	"nstance.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"3\n" +
	"\x14KeyGenerationRequest\x12\x1b\n" +
	"\tkey_names\x18\x01 \x03(\tR\bkeyNames\"i\n" +
	"\x11PublicKeysRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x123\n" +
	"\x04keys\x18\x02 \x03(\v2\x1f.nstance.v1.PublicKeySubmissionR\x04keys\"W\n" +
	"\x13PublicKeySubmission\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12$\n" +
	"\x0epublic_key_pem\x18\x02 \x01(\fR\fpublicKeyPem\"\x95\x06\n" +
	"\x13HealthReportRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x03R\x05count\x124\n" +
	"\astarted\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\astarted\x12=\n" +
	"\fwindow_start\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vwindowStart\x129\n" +
	"\n" +
	"window_end\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\twindowEnd\x12\x16\n" +
	"\x06uptime\x18\b \x01(\tR\x06uptime\x122\n" +
	"\n" +
	"one_minute\x18\t \x01(\v2\x13.nstance.v1.MetricsR\toneMinute\x126\n" +
	"\ffive_minutes\x18\n" +
	" \x01(\v2\x13.nstance.v1.MetricsR\vfiveMinutes\x12<\n" +
	"\x0ffifteen_minutes\x18\v \x01(\v2\x13.nstance.v1.MetricsR\x0efifteenMinutes\x12@\n" +
	"\x05files\x18\f \x03(\v2*.nstance.v1.HealthReportRequest.FilesEntryR\x05files\x12L\n" +
	"\x12termination_notice\x18\r \x01(\v2\x1d.nstance.v1.TerminationNoticeR\x11terminationNotice\x12\x1f\n" +
	"\vconfig_hash\x18\x0e \x01(\tR\n" +
	"configHash\x1aP\n" +
	"\n" +
	"FilesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.nstance.v1.FileStatusR\x05value:\x028\x01\"\xf0\x02\n" +
	"\aMetrics\x12\x1b\n" +
	"\tcpu_usage\x18\x01 \x01(\x01R\bcpuUsage\x12$\n" +
	"\x0ecpu_core_usage\x18\x02 \x03(\x01R\fcpuCoreUsage\x12!\n" +
	"\fmemory_usage\x18\x03 \x01(\x01R\vmemoryUsage\x12,\n" +
	"\x12network_bytes_sent\x18\x04 \x01(\x01R\x10networkBytesSent\x124\n" +
	"\x16network_bytes_received\x18\x05 \x01(\x01R\x14networkBytesReceived\x12\x1b\n" +
	"\tdisk_used\x18\x06 \x01(\x01R\bdiskUsed\x12(\n" +
	"\x10disk_inodes_used\x18\a \x01(\x01R\x0ediskInodesUsed\x12&\n" +
	"\x0fdisk_bytes_read\x18\b \x01(\x01R\rdiskBytesRead\x12,\n" +
	"\x12disk_bytes_written\x18\t \x01(\x01R\x10diskBytesWritten\"q\n" +
	"\n" +
	"FileStatus\x12A\n" +
	"\rlast_modified\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\flastModified\x12\x16\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05errorB\b\n" +
	"\x06status\"c\n" +
	"\x11TerminationNotice\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x126\n" +
	"\bdeadline\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\bdeadline\"\xa6\x01\n" +
	"\fFileTransfer\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\x12?\n" +
	"\rlast_modified\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\flastModified\x12\x1f\n" +
	"\vconfig_hash\x18\x04 \x01(\tR\n" +
	"configHash2\xc0\x02\n" +
	"\fAgentService\x12P\n" +
	"\x12ReceiveKeyRequests\x12\x16.google.protobuf.Empty\x1a .nstance.v1.KeyGenerationRequest0\x01\x12I\n" +
	"\x10SubmitPublicKeys\x12\x1d.nstance.v1.PublicKeysRequest\x1a\x16.google.protobuf.Empty\x12O\n" +
	"\x12SubmitHealthReport\x12\x1f.nstance.v1.HealthReportRequest\x1a\x16.google.protobuf.Empty(\x01\x12B\n" +
	"\fReceiveFiles\x12\x16.google.protobuf.Empty\x1a\x18.nstance.v1.FileTransfer0\x01B/Z-github.com/nstance-dev/nstance/internal/protob\x06proto3"

var (
	file_proto_agent_proto_rawDescOnce sync.Once
	file_proto_agent_proto_rawDescData []byte
)

func file_proto_agent_proto_rawDescGZIP() []byte {
	file_proto_agent_proto_rawDescOnce.Do(func() {
		file_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)))
	})
	return file_proto_agent_proto_rawDescData
}

var file_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_agent_proto_goTypes = []any{
	(*KeyGenerationRequest)(nil),  // 0: nstance.v1.KeyGenerationRequest
	(*PublicKeysRequest)(nil),     // 1: nstance.v1.PublicKeysRequest
	(*PublicKeySubmission)(nil),   // 2: nstance.v1.PublicKeySubmission
	(*HealthReportRequest)(nil),   // 3: nstance.v1.HealthReportRequest
	(*Metrics)(nil),               // 4: nstance.v1.Metrics
	(*FileStatus)(nil),            // 5: nstance.v1.FileStatus
	(*TerminationNotice)(nil),     // 6: nstance.v1.TerminationNotice
	(*FileTransfer)(nil),          // 7: nstance.v1.FileTransfer
	nil,                           // 8: nstance.v1.HealthReportRequest.FilesEntry
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 10: google.protobuf.Empty
}
var file_proto_agent_proto_depIdxs = []int32{
	2,  // 0: nstance.v1.PublicKeysRequest.keys:type_name -> nstance.v1.PublicKeySubmission
	9,  // 1: nstance.v1.HealthReportRequest.timestamp:type_name -> google.protobuf.Timestamp
	9,  // 2: nstance.v1.HealthReportRequest.started:type_name -> google.protobuf.Timestamp
	9,  // 3: nstance.v1.HealthReportRequest.window_start:type_name -> google.protobuf.Timestamp
	9,  // 4: nstance.v1.HealthReportRequest.window_end:type_name -> google.protobuf.Timestamp
	4,  // 5: nstance.v1.HealthReportRequest.one_minute:type_name -> nstance.v1.Metrics
	4,  // 6: nstance.v1.HealthReportRequest.five_minutes:type_name -> nstance.v1.Metrics
	4,  // 7: nstance.v1.HealthReportRequest.fifteen_minutes:type_name -> nstance.v1.Metrics
	8,  // 8: nstance.v1.HealthReportRequest.files:type_name -> nstance.v1.HealthReportRequest.FilesEntry
	6,  // 9: nstance.v1.HealthReportRequest.termination_notice:type_name -> nstance.v1.TerminationNotice
	9,  // 10: nstance.v1.FileStatus.last_modified:type_name -> google.protobuf.Timestamp
	9,  // 11: nstance.v1.TerminationNotice.deadline:type_name -> google.protobuf.Timestamp
	9,  // 12: nstance.v1.FileTransfer.last_modified:type_name -> google.protobuf.Timestamp
	5,  // 13: nstance.v1.HealthReportRequest.FilesEntry.value:type_name -> nstance.v1.FileStatus
	10, // 14: nstance.v1.AgentService.ReceiveKeyRequests:input_type -> google.protobuf.Empty
	1,  // 15: nstance.v1.AgentService.SubmitPublicKeys:input_type -> nstance.v1.PublicKeysRequest
	3,  // 16: nstance.v1.AgentService.SubmitHealthReport:input_type -> nstance.v1.HealthReportRequest
	10, // 17: nstance.v1.AgentService.ReceiveFiles:input_type -> google.protobuf.Empty
	0,  // 18: nstance.v1.AgentService.ReceiveKeyRequests:output_type -> nstance.v1.KeyGenerationRequest
	10, // 19: nstance.v1.AgentService.SubmitPublicKeys:output_type -> google.protobuf.Empty
	10, // 20: nstance.v1.AgentService.SubmitHealthReport:output_type -> google.protobuf.Empty
	7,  // 21: nstance.v1.AgentService.ReceiveFiles:output_type -> nstance.v1.FileTransfer
	18, // [18:22] is the sub-list for method output_type
	14, // [14:18] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_proto_agent_proto_init() }
func file_proto_agent_proto_init() {
	if File_proto_agent_proto != nil {
		return
	}
	file_proto_agent_proto_msgTypes[5].OneofWrappers = []any{
		(*FileStatus_LastModified)(nil),
		(*FileStatus_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agent_proto_goTypes,
		DependencyIndexes: file_proto_agent_proto_depIdxs,
		MessageInfos:      file_proto_agent_proto_msgTypes,
	}.Build()
	File_proto_agent_proto = out.File
	file_proto_agent_proto_goTypes = nil
	file_proto_agent_proto_depIdxs = nil
}
