// Nstance <https://nstance.dev>
// Copyright 2026 Nadrama Pty Ltd
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: proto/operator.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GroupEvent_Type int32

const (
	GroupEvent_UPSERT GroupEvent_Type = 0
	GroupEvent_DELETE GroupEvent_Type = 1
)

// Enum value maps for GroupEvent_Type.
var (
	GroupEvent_Type_name = map[int32]string{
		0: "UPSERT",
		1: "DELETE",
	}
	GroupEvent_Type_value = map[string]int32{
		"UPSERT": 0,
		"DELETE": 1,
	}
)

func (x GroupEvent_Type) Enum() *GroupEvent_Type {
	p := new(GroupEvent_Type)
	*p = x
	return p
}

func (x GroupEvent_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GroupEvent_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_operator_proto_enumTypes[0].Descriptor()
}

func (GroupEvent_Type) Type() protoreflect.EnumType {
	return &file_proto_operator_proto_enumTypes[0]
}

func (x GroupEvent_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GroupEvent_Type.Descriptor instead.
func (GroupEvent_Type) EnumDescriptor() ([]byte, []int) {
	return file_proto_operator_proto_rawDescGZIP(), []int{16, 0}
}

// Certificate renewal request
type RenewCertificateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKeyPem  []byte                 `protobuf:"bytes,1,opt,name=public_key_pem,json=publicKeyPem,proto3" json:"public_key_pem,omitempty"` // Same or new public key
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewCertificateRequest) Reset() {
	*x = RenewCertificateRequest{}
	mi := &file_proto_operator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewCertificateRequest) ProtoMessage() {}

func (x *RenewCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewCertificateRequest.ProtoReflect.Descriptor instead.
func (*RenewCertificateRequest) Descriptor() ([]byte, []int) {
	return file_proto_operator_proto_rawDescGZIP(), []int{0}
}

func (x *RenewCertificateRequest) GetPublicKeyPem() []byte {
	if x != nil {
		return x.PublicKeyPem
	}
	return nil
}

// Certificate renewal response
type RenewCertificateResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ClientCertificatePem []byte                 `protobuf:"bytes,1,opt,name=client_certificate_pem,json=clientCertificatePem,proto3" json:"client_certificate_pem,omitempty"`
	ExpiresAt            *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RenewCertificateResponse) Reset() {
	*x = RenewCertificateResponse{}
	mi := &file_proto_operator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewCertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewCertificateResponse) ProtoMessage() {}

func (x *RenewCertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewCertificateResponse.ProtoReflect.Descriptor instead.
func (*RenewCertificateResponse) Descriptor() ([]byte, []int) {
	return file_proto_operator_proto_rawDescGZIP(), []int{1}
}

func (x *RenewCertificateResponse) GetClientCertificatePem() []byte {
	if x != nil {
		return x.ClientCertificatePem
	}
	return nil
}

func (x *RenewCertificateResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type ConfigStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Etag          string                 `protobuf:"bytes,1,opt,name=etag,proto3" json:"etag,omitempty"`
	LastModified  *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=last_modified,json=lastModified,proto3" json:"last_modified,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigStatusResponse) Reset() {
	*x = ConfigStatusResponse{}
	mi := &file_proto_operator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigStatusResponse) ProtoMessage() {}

func (x *ConfigStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigStatusResponse.ProtoReflect.Descriptor instead.
func (*ConfigStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_operator_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigStatusResponse) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *ConfigStatusResponse) GetLastModified() *timestamppb.Timestamp {
	if x != nil {
		return x.LastModified
	}
	return nil
}

func (x *ConfigStatusResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// RefreshConfig response
type RefreshConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Updated       bool                   `protobuf:"varint,1,opt,name=updated,proto3" json:"updated,omitempty"`                  // true if config was updated, false if unchanged
	PrevEtag      string                 `protobuf:"bytes,2,opt,name=prev_etag,json=prevEtag,proto3" json:"prev_etag,omitempty"` // Config etag before refresh
	Etag          string                 `protobuf:"bytes,3,opt,name=etag,proto3" json:"etag,omitempty"`                         // Config etag after refresh
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshConfigResponse) Reset() {
	*x = RefreshConfigResponse{}
	mi := &file_proto_operator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshConfigResponse) ProtoMessage() {}

func (x *RefreshConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshConfigResponse.ProtoReflect.Descriptor instead.
func (*RefreshConfigResponse) Descriptor() ([]byte, []int) {
	return file_proto_operator_proto_rawDescGZIP(), []int{3}
}

func (x *RefreshConfigResponse) GetUpdated() bool {
	if x != nil {
		return x.Updated
	}
	return false
}

func (x *RefreshConfigResponse) GetPrevEtag() string {
	if x != nil {
		return x.PrevEtag
	}
	return ""
}

func (x *RefreshConfigResponse) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

type UpsertGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Config        *GroupConfig           `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpsertGroupRequest) Reset() {
	*x = UpsertGroupRequest{}
	mi := &file_proto_operator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpsertGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertGroupRequest) ProtoMessage() {}

func (x *UpsertGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertGroupRequest.ProtoReflect.Descriptor instead.
func (*UpsertGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_operator_proto_rawDescGZIP(), []int{4}
}

func (x *UpsertGroupRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *UpsertGroupRequest) GetConfig() *GroupConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type GroupConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Template      string                 `protobuf:"bytes,1,opt,name=template,proto3" json:"template,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	InstanceType  string                 `protobuf:"bytes,3,opt,name=instance_type,json=instanceType,proto3" json:"instance_type,omitempty"`
	SubnetPool    string                 `protobuf:"bytes,4,opt,name=subnet_pool,json=subnetPool,proto3" json:"subnet_pool,omitempty"` // Logical subnet pool ID (references server.subnet_pools map key)
	Vars          map[string]string      `protobuf:"bytes,5,rep,name=vars,proto3" json:"vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Args          map[string]string      `protobuf:"bytes,6,rep,name=args,proto3" json:"args,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Group-level overrides
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupConfig) Reset() {
	*x = GroupConfig{}
	mi := &file_proto_operator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupConfig) ProtoMessage() {}

func (x *GroupConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupConfig.ProtoReflect.Descriptor instead.
func (*GroupConfig) Descriptor() ([]byte, []int) {
	return file_proto_operator_proto_rawDescGZIP(), []int{5}
}

func (x *GroupConfig) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *GroupConfig) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GroupConfig) GetInstanceType() string {
	if x != nil {
		return x.InstanceType
	}
	return ""
}

func (x *GroupConfig) GetSubnetPool() string {
	if x != nil {
		return x.SubnetPool
	}
	return ""
}

func (x *GroupConfig) GetVars() map[string]string {
	if x != nil {
		return x.Vars
	}
	return nil
}

func (x *GroupConfig) GetArgs() map[string]string {
	if x != nil {
		return x.Args
	}
	return nil
}

type DeleteGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGroupRequest) Reset() {
	*x = DeleteGroupRequest{}
	mi := &file_proto_operator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupRequest) ProtoMessage() {}

func (x *DeleteGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupRequest.ProtoReflect.Descriptor instead.
func (*DeleteGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_operator_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteGroupRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ListGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*GroupStatus         `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupsResponse) Reset() {
	*x = ListGroupsResponse{}
	mi := &file_proto_operator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsResponse) ProtoMessage() {}

func (x *ListGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListGroupsResponse) Descriptor() ([]byte, []int) {
	return file_proto_operator_proto_rawDescGZIP(), []int{7}
}

func (x *ListGroupsResponse) GetGroups() []*GroupStatus {
	if x != nil {
		return x.Groups
	}
	return nil
}

type GroupStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`                                                                             // Group name/key
	Tenant        string                 `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`                                                                       // Tenant identifier
	Template      string                 `protobuf:"bytes,3,opt,name=template,proto3" json:"template,omitempty"`                                                                   // Instance template used
	Size          int32                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`                                                                          // Desired size
	InstanceType  string                 `protobuf:"bytes,5,opt,name=instance_type,json=instanceType,proto3" json:"instance_type,omitempty"`                                       // Instance type (from template or override)
	SubnetPool    string                 `protobuf:"bytes,6,opt,name=subnet_pool,json=subnetPool,proto3" json:"subnet_pool,omitempty"`                                             // Logical subnet pool ID for this group
	Vars          map[string]string      `protobuf:"bytes,7,rep,name=vars,proto3" json:"vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Merged vars
	IsStatic      bool                   `protobuf:"varint,8,opt,name=is_static,json=isStatic,proto3" json:"is_static,omitempty"`                                                  // Whether group is defined in static config
	Etag          string                 `protobuf:"bytes,9,opt,name=etag,proto3" json:"etag,omitempty"`                                                                           // Hash of this group's merged config for change detection
	ActualSize    int32                  `protobuf:"varint,10,opt,name=actual_size,json=actualSize,proto3" json:"actual_size,omitempty"`                                           // Number of currently running instances
	ProviderIds   []string               `protobuf:"bytes,11,rep,name=provider_ids,json=providerIds,proto3" json:"provider_ids,omitempty"`                                         // Provider IDs of running instances (sorted)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupStatus) Reset() {
	*x = GroupStatus{}
	mi := &file_proto_operator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupStatus) ProtoMessage() {}

func (x *GroupStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupStatus.ProtoReflect.Descriptor instead.
func (*GroupStatus) Descriptor() ([]byte, []int) {
	return file_proto_operator_proto_rawDescGZIP(), []int{8}
}

func (x *GroupStatus) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GroupStatus) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *GroupStatus) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *GroupStatus) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GroupStatus) GetInstanceType() string {
	if x != nil {
		return x.InstanceType
	}
	return ""
}

func (x *GroupStatus) GetSubnetPool() string {
	if x != nil {
		return x.SubnetPool
	}
	return ""
}

func (x *GroupStatus) GetVars() map[string]string {
	if x != nil {
		return x.Vars
	}
	return nil
}

func (x *GroupStatus) GetIsStatic() bool {
	if x != nil {
		return x.IsStatic
	}
	return false
}

func (x *GroupStatus) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *GroupStatus) GetActualSize() int32 {
	if x != nil {
		return x.ActualSize
	}
	return 0
}

func (x *GroupStatus) GetProviderIds() []string {
	if x != nil {
		return x.ProviderIds
	}
	return nil
}

type CreateInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"` // If empty, server generates one
	Config        *InstanceConfig        `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInstanceRequest) Reset() {
	*x = CreateInstanceRequest{}
	mi := &file_proto_operator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInstanceRequest) ProtoMessage() {}

func (x *CreateInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInstanceRequest.ProtoReflect.Descriptor instead.
func (*CreateInstanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_operator_proto_rawDescGZIP(), []int{9}
}

func (x *CreateInstanceRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *CreateInstanceRequest) GetConfig() *InstanceConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

type InstanceConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`                                                                         // Required group reference
	Template      string                 `protobuf:"bytes,2,opt,name=template,proto3" json:"template,omitempty"`                                                                   // Optional template override
	InstanceType  string                 `protobuf:"bytes,3,opt,name=instance_type,json=instanceType,proto3" json:"instance_type,omitempty"`                                       // Optional instance type override
	SubnetPool    string                 `protobuf:"bytes,4,opt,name=subnet_pool,json=subnetPool,proto3" json:"subnet_pool,omitempty"`                                             // Optional subnet pool override
	Vars          map[string]string      `protobuf:"bytes,5,rep,name=vars,proto3" json:"vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Additional vars
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceConfig) Reset() {
	*x = InstanceConfig{}
	mi := &file_proto_operator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceConfig) ProtoMessage() {}

func (x *InstanceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceConfig.ProtoReflect.Descriptor instead.
func (*InstanceConfig) Descriptor() ([]byte, []int) {
	return file_proto_operator_proto_rawDescGZIP(), []int{10}
}

func (x *InstanceConfig) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *InstanceConfig) GetTemplate() string {
	if x != nil {
		return x.Template
	}
	return ""
}

func (x *InstanceConfig) GetInstanceType() string {
	if x != nil {
		return x.InstanceType
	}
	return ""
}

func (x *InstanceConfig) GetSubnetPool() string {
	if x != nil {
		return x.SubnetPool
	}
	return ""
}

func (x *InstanceConfig) GetVars() map[string]string {
	if x != nil {
		return x.Vars
	}
	return nil
}

type CreateInstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"` // Generated or confirmed instance ID
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                           // Current instance status
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInstanceResponse) Reset() {
	*x = CreateInstanceResponse{}
	mi := &file_proto_operator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInstanceResponse) ProtoMessage() {}

func (x *CreateInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInstanceResponse.ProtoReflect.Descriptor instead.
func (*CreateInstanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_operator_proto_rawDescGZIP(), []int{11}
}

func (x *CreateInstanceResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *CreateInstanceResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DeleteInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteInstanceRequest) Reset() {
	*x = DeleteInstanceRequest{}
	mi := &file_proto_operator_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInstanceRequest) ProtoMessage() {}

func (x *DeleteInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operator_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInstanceRequest.ProtoReflect.Descriptor instead.
func (*DeleteInstanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_operator_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteInstanceRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type DeleteInstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // "deleting", "deleted", "unknown"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteInstanceResponse) Reset() {
	*x = DeleteInstanceResponse{}
	mi := &file_proto_operator_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteInstanceResponse) ProtoMessage() {}

func (x *DeleteInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operator_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteInstanceResponse.ProtoReflect.Descriptor instead.
func (*DeleteInstanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_operator_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteInstanceResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetInstanceStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstanceStatusRequest) Reset() {
	*x = GetInstanceStatusRequest{}
	mi := &file_proto_operator_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstanceStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstanceStatusRequest) ProtoMessage() {}

func (x *GetInstanceStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operator_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstanceStatusRequest.ProtoReflect.Descriptor instead.
func (*GetInstanceStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_operator_proto_rawDescGZIP(), []int{14}
}

func (x *GetInstanceStatusRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type InstanceStatusResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	InstanceId         string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Tenant             string                 `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"` // Tenant identifier
	Status             string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // "pending", "running", "terminating", "terminated", etc.
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastSeen           *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	ProviderInstanceId string                 `protobuf:"bytes,6,opt,name=provider_instance_id,json=providerInstanceId,proto3" json:"provider_instance_id,omitempty"` // e.g., EC2 instance ID
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *InstanceStatusResponse) Reset() {
	*x = InstanceStatusResponse{}
	mi := &file_proto_operator_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceStatusResponse) ProtoMessage() {}

func (x *InstanceStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operator_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceStatusResponse.ProtoReflect.Descriptor instead.
func (*InstanceStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_operator_proto_rawDescGZIP(), []int{15}
}

func (x *InstanceStatusResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *InstanceStatusResponse) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *InstanceStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *InstanceStatusResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *InstanceStatusResponse) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *InstanceStatusResponse) GetProviderInstanceId() string {
	if x != nil {
		return x.ProviderInstanceId
	}
	return ""
}

// Group change event
type GroupEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          GroupEvent_Type        `protobuf:"varint,1,opt,name=type,proto3,enum=nstance.v1.GroupEvent_Type" json:"type,omitempty"`
	Group         *GroupStatus           `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"` // For UPSERT: full group status. For DELETE: only key is set.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupEvent) Reset() {
	*x = GroupEvent{}
	mi := &file_proto_operator_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupEvent) ProtoMessage() {}

func (x *GroupEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operator_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupEvent.ProtoReflect.Descriptor instead.
func (*GroupEvent) Descriptor() ([]byte, []int) {
	return file_proto_operator_proto_rawDescGZIP(), []int{16}
}

func (x *GroupEvent) GetType() GroupEvent_Type {
	if x != nil {
		return x.Type
	}
	return GroupEvent_UPSERT
}

func (x *GroupEvent) GetGroup() *GroupStatus {
	if x != nil {
		return x.Group
	}
	return nil
}

type InstanceEvent struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	InstanceId         string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Tenant             string                 `protobuf:"bytes,2,opt,name=tenant,proto3" json:"tenant,omitempty"`                                                     // Tenant identifier
	ProviderInstanceId string                 `protobuf:"bytes,3,opt,name=provider_instance_id,json=providerInstanceId,proto3" json:"provider_instance_id,omitempty"` // Provider's instance ID (e.g., i-1234567890abcdef0) for node mapping
	Group              string                 `protobuf:"bytes,4,opt,name=group,proto3" json:"group,omitempty"`
	Status             string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`                              // "pending_deletion", "deleting", "deleted"
	Reason             string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`                              // Why instance is being deleted (e.g., "unhealthy")
	UnhealthyAt        *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=unhealthy_at,json=unhealthyAt,proto3" json:"unhealthy_at,omitempty"` // When instance was determined unhealthy
	DeleteAt           *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=delete_at,json=deleteAt,proto3" json:"delete_at,omitempty"`          // When instance will be deleted (drain_timeout from unhealthy_at)
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *InstanceEvent) Reset() {
	*x = InstanceEvent{}
	mi := &file_proto_operator_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceEvent) ProtoMessage() {}

func (x *InstanceEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operator_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceEvent.ProtoReflect.Descriptor instead.
func (*InstanceEvent) Descriptor() ([]byte, []int) {
	return file_proto_operator_proto_rawDescGZIP(), []int{17}
}

func (x *InstanceEvent) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *InstanceEvent) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *InstanceEvent) GetProviderInstanceId() string {
	if x != nil {
		return x.ProviderInstanceId
	}
	return ""
}

func (x *InstanceEvent) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *InstanceEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *InstanceEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *InstanceEvent) GetUnhealthyAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UnhealthyAt
	}
	return nil
}

func (x *InstanceEvent) GetDeleteAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeleteAt
	}
	return nil
}

type DrainAckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DrainAckRequest) Reset() {
	*x = DrainAckRequest{}
	mi := &file_proto_operator_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DrainAckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrainAckRequest) ProtoMessage() {}

func (x *DrainAckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operator_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrainAckRequest.ProtoReflect.Descriptor instead.
func (*DrainAckRequest) Descriptor() ([]byte, []int) {
	return file_proto_operator_proto_rawDescGZIP(), []int{18}
}

func (x *DrainAckRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

// Error event for provider errors, config validation failures, etc.
type ErrorEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`                             // Affected group (optional)
	InstanceId    string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"` // Affected instance (optional)
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`                             // Error message
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                     // When the error occurred
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorEvent) Reset() {
	*x = ErrorEvent{}
	mi := &file_proto_operator_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorEvent) ProtoMessage() {}

func (x *ErrorEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operator_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorEvent.ProtoReflect.Descriptor instead.
func (*ErrorEvent) Descriptor() ([]byte, []int) {
	return file_proto_operator_proto_rawDescGZIP(), []int{19}
}

func (x *ErrorEvent) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *ErrorEvent) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *ErrorEvent) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ErrorEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_proto_operator_proto protoreflect.FileDescriptor

const file_proto_operator_proto_rawDesc = "" +
	"\n" +
	"\x14proto/operator.proto\x12\n" +
	"nstance.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"?\n" +
	"\x17RenewCertificateRequest\x12$\n" +
	"\x0epublic_key_pem\x18\x01 \x01(\fR\fpublicKeyPem\"\x8b\x01\n" +
	"\x18RenewCertificateResponse\x124\n" +
	"\x16client_certificate_pem\x18\x01 \x01(\fR\x14clientCertificatePem\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\x7f\n" +
	"\x14ConfigStatusResponse\x12\x12\n" +
	"\x04etag\x18\x01 \x01(\tR\x04etag\x12?\n" +
	"\rlast_modified\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\flastModified\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\"b\n" +
	"\x15RefreshConfigResponse\x12\x18\n" +
	"\aupdated\x18\x01 \x01(\bR\aupdated\x12\x1b\n" +
	"\tprev_etag\x18\x02 \x01(\tR\bprevEtag\x12\x12\n" +
	"\x04etag\x18\x03 \x01(\tR\x04etag\"W\n" +
	"\x12UpsertGroupRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x06config\x18\x02 \x01(\v2\x17.nstance.v1.GroupConfigR\x06config\"\xe3\x02\n" +
	"\vGroupConfig\x12\x1a\n" +
	"\btemplate\x18\x01 \x01(\tR\btemplate\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12#\n" +
	"\rinstance_type\x18\x03 \x01(\tR\finstanceType\x12\x1f\n" +
	"\vsubnet_pool\x18\x04 \x01(\tR\n" +
	"subnetPool\x125\n" +
	"\x04vars\x18\x05 \x03(\v2!.nstance.v1.GroupConfig.VarsEntryR\x04vars\x125\n" +
	"\x04args\x18\x06 \x03(\v2!.nstance.v1.GroupConfig.ArgsEntryR\x04args\x1a7\n" +
	"\tVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a7\n" +
	"\tArgsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"&\n" +
	"\x12DeleteGroupRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"E\n" +
	"\x12ListGroupsResponse\x12/\n" +
	"\x06groups\x18\x01 \x03(\v2\x17.nstance.v1.GroupStatusR\x06groups\"\x92\x03\n" +
	"\vGroupStatus\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06tenant\x18\x02 \x01(\tR\x06tenant\x12\x1a\n" +
	"\btemplate\x18\x03 \x01(\tR\btemplate\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x05R\x04size\x12#\n" +
	"\rinstance_type\x18\x05 \x01(\tR\finstanceType\x12\x1f\n" +
	"\vsubnet_pool\x18\x06 \x01(\tR\n" +
	"subnetPool\x125\n" +
	"\x04vars\x18\a \x03(\v2!.nstance.v1.GroupStatus.VarsEntryR\x04vars\x12\x1b\n" +
	"\tis_static\x18\b \x01(\bR\bisStatic\x12\x12\n" +
	"\x04etag\x18\t \x01(\tR\x04etag\x12\x1f\n" +
	"\vactual_size\x18\n" +
	" \x01(\x05R\n" +
	"actualSize\x12!\n" +
	"\fprovider_ids\x18\v \x03(\tR\vproviderIds\x1a7\n" +
	"\tVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"l\n" +
	"\x15CreateInstanceRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x122\n" +
	"\x06config\x18\x02 \x01(\v2\x1a.nstance.v1.InstanceConfigR\x06config\"\xfb\x01\n" +
	"\x0eInstanceConfig\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x1a\n" +
	"\btemplate\x18\x02 \x01(\tR\btemplate\x12#\n" +
	"\rinstance_type\x18\x03 \x01(\tR\finstanceType\x12\x1f\n" +
	"\vsubnet_pool\x18\x04 \x01(\tR\n" +
	"subnetPool\x128\n" +
	"\x04vars\x18\x05 \x03(\v2$.nstance.v1.InstanceConfig.VarsEntryR\x04vars\x1a7\n" +
	"\tVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Q\n" +
	"\x16CreateInstanceResponse\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"8\n" +
	"\x15DeleteInstanceRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\"0\n" +
	"\x16DeleteInstanceResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\";\n" +
	"\x18GetInstanceStatusRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\"\x8f\x02\n" +
	"\x16InstanceStatusResponse\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x16\n" +
	"\x06tenant\x18\x02 \x01(\tR\x06tenant\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x127\n" +
	"\tlast_seen\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x120\n" +
	"\x14provider_instance_id\x18\x06 \x01(\tR\x12providerInstanceId\"\x8c\x01\n" +
	"\n" +
	"GroupEvent\x12/\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1b.nstance.v1.GroupEvent.TypeR\x04type\x12-\n" +
	"\x05group\x18\x02 \x01(\v2\x17.nstance.v1.GroupStatusR\x05group\"\x1e\n" +
	"\x04Type\x12\n" +
	"\n" +
	"\x06UPSERT\x10\x00\x12\n" +
	"\n" +
	"\x06DELETE\x10\x01\"\xb8\x02\n" +
	"\rInstanceEvent\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x16\n" +
	"\x06tenant\x18\x02 \x01(\tR\x06tenant\x120\n" +
	"\x14provider_instance_id\x18\x03 \x01(\tR\x12providerInstanceId\x12\x14\n" +
	"\x05group\x18\x04 \x01(\tR\x05group\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\x12=\n" +
	"\funhealthy_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vunhealthyAt\x127\n" +
	"\tdelete_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\bdeleteAt\"2\n" +
	"\x0fDrainAckRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\"\x93\x01\n" +
	"\n" +
	"ErrorEvent\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp2\x83\b\n" +
	"\x0fOperatorService\x12]\n" +
	"\x10RenewCertificate\x12#.nstance.v1.RenewCertificateRequest\x1a$.nstance.v1.RenewCertificateResponse\x12K\n" +
	"\x0fGetConfigStatus\x12\x16.google.protobuf.Empty\x1a .nstance.v1.ConfigStatusResponse\x12J\n" +
	"\rRefreshConfig\x12\x16.google.protobuf.Empty\x1a!.nstance.v1.RefreshConfigResponse\x12D\n" +
	"\n" +
	"ListGroups\x12\x16.google.protobuf.Empty\x1a\x1e.nstance.v1.ListGroupsResponse\x12F\n" +
	"\vUpsertGroup\x12\x1e.nstance.v1.UpsertGroupRequest\x1a\x17.nstance.v1.GroupStatus\x12E\n" +
	"\vDeleteGroup\x12\x1e.nstance.v1.DeleteGroupRequest\x1a\x16.google.protobuf.Empty\x12W\n" +
	"\x0eCreateInstance\x12!.nstance.v1.CreateInstanceRequest\x1a\".nstance.v1.CreateInstanceResponse\x12W\n" +
	"\x0eDeleteInstance\x12!.nstance.v1.DeleteInstanceRequest\x1a\".nstance.v1.DeleteInstanceResponse\x12]\n" +
	"\x11GetInstanceStatus\x12$.nstance.v1.GetInstanceStatusRequest\x1a\".nstance.v1.InstanceStatusResponse\x12I\n" +
	"\x12AcknowledgeDrained\x12\x1b.nstance.v1.DrainAckRequest\x1a\x16.google.protobuf.Empty\x12?\n" +
	"\vWatchGroups\x12\x16.google.protobuf.Empty\x1a\x16.nstance.v1.GroupEvent0\x01\x12E\n" +
	"\x0eWatchInstances\x12\x16.google.protobuf.Empty\x1a\x19.nstance.v1.InstanceEvent0\x01\x12?\n" +
	"\vWatchErrors\x12\x16.google.protobuf.Empty\x1a\x16.nstance.v1.ErrorEvent0\x01B/Z-github.com/nstance-dev/nstance/internal/protob\x06proto3"

var (
	file_proto_operator_proto_rawDescOnce sync.Once
	file_proto_operator_proto_rawDescData []byte
)

func file_proto_operator_proto_rawDescGZIP() []byte {
	file_proto_operator_proto_rawDescOnce.Do(func() {
		file_proto_operator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_operator_proto_rawDesc), len(file_proto_operator_proto_rawDesc)))
	})
	return file_proto_operator_proto_rawDescData
}

var file_proto_operator_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_operator_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_proto_operator_proto_goTypes = []any{
	(GroupEvent_Type)(0),             // 0: nstance.v1.GroupEvent.Type
	(*RenewCertificateRequest)(nil),  // 1: nstance.v1.RenewCertificateRequest
	(*RenewCertificateResponse)(nil), // 2: nstance.v1.RenewCertificateResponse
	(*ConfigStatusResponse)(nil),     // 3: nstance.v1.ConfigStatusResponse
	(*RefreshConfigResponse)(nil),    // 4: nstance.v1.RefreshConfigResponse
	(*UpsertGroupRequest)(nil),       // 5: nstance.v1.UpsertGroupRequest
	(*GroupConfig)(nil),              // 6: nstance.v1.GroupConfig
	(*DeleteGroupRequest)(nil),       // 7: nstance.v1.DeleteGroupRequest
	(*ListGroupsResponse)(nil),       // 8: nstance.v1.ListGroupsResponse
	(*GroupStatus)(nil),              // 9: nstance.v1.GroupStatus
	(*CreateInstanceRequest)(nil),    // 10: nstance.v1.CreateInstanceRequest
	(*InstanceConfig)(nil),           // 11: nstance.v1.InstanceConfig
	(*CreateInstanceResponse)(nil),   // 12: nstance.v1.CreateInstanceResponse
	(*DeleteInstanceRequest)(nil),    // 13: nstance.v1.DeleteInstanceRequest
	(*DeleteInstanceResponse)(nil),   // 14: nstance.v1.DeleteInstanceResponse
	(*GetInstanceStatusRequest)(nil), // 15: nstance.v1.GetInstanceStatusRequest
	(*InstanceStatusResponse)(nil),   // 16: nstance.v1.InstanceStatusResponse
	(*GroupEvent)(nil),               // 17: nstance.v1.GroupEvent
	(*InstanceEvent)(nil),            // 18: nstance.v1.InstanceEvent
	(*DrainAckRequest)(nil),          // 19: nstance.v1.DrainAckRequest
	(*ErrorEvent)(nil),               // 20: nstance.v1.ErrorEvent
	nil,                              // 21: nstance.v1.GroupConfig.VarsEntry
	nil,                              // 22: nstance.v1.GroupConfig.ArgsEntry
	nil,                              // 23: nstance.v1.GroupStatus.VarsEntry
	nil,                              // 24: nstance.v1.InstanceConfig.VarsEntry
	(*timestamppb.Timestamp)(nil),    // 25: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),            // 26: google.protobuf.Empty
}
var file_proto_operator_proto_depIdxs = []int32{
	25, // 0: nstance.v1.RenewCertificateResponse.expires_at:type_name -> google.protobuf.Timestamp
	25, // 1: nstance.v1.ConfigStatusResponse.last_modified:type_name -> google.protobuf.Timestamp
	6,  // 2: nstance.v1.UpsertGroupRequest.config:type_name -> nstance.v1.GroupConfig
	21, // 3: nstance.v1.GroupConfig.vars:type_name -> nstance.v1.GroupConfig.VarsEntry
	22, // 4: nstance.v1.GroupConfig.args:type_name -> nstance.v1.GroupConfig.ArgsEntry
	9,  // 5: nstance.v1.ListGroupsResponse.groups:type_name -> nstance.v1.GroupStatus
	23, // 6: nstance.v1.GroupStatus.vars:type_name -> nstance.v1.GroupStatus.VarsEntry
	11, // 7: nstance.v1.CreateInstanceRequest.config:type_name -> nstance.v1.InstanceConfig
	24, // 8: nstance.v1.InstanceConfig.vars:type_name -> nstance.v1.InstanceConfig.VarsEntry
	25, // 9: nstance.v1.InstanceStatusResponse.created_at:type_name -> google.protobuf.Timestamp
	25, // 10: nstance.v1.InstanceStatusResponse.last_seen:type_name -> google.protobuf.Timestamp
	0,  // 11: nstance.v1.GroupEvent.type:type_name -> nstance.v1.GroupEvent.Type
	9,  // 12: nstance.v1.GroupEvent.group:type_name -> nstance.v1.GroupStatus
	25, // 13: nstance.v1.InstanceEvent.unhealthy_at:type_name -> google.protobuf.Timestamp
	25, // 14: nstance.v1.InstanceEvent.delete_at:type_name -> google.protobuf.Timestamp
	25, // 15: nstance.v1.ErrorEvent.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 16: nstance.v1.OperatorService.RenewCertificate:input_type -> nstance.v1.RenewCertificateRequest
	26, // 17: nstance.v1.OperatorService.GetConfigStatus:input_type -> google.protobuf.Empty
	26, // 18: nstance.v1.OperatorService.RefreshConfig:input_type -> google.protobuf.Empty
	26, // 19: nstance.v1.OperatorService.ListGroups:input_type -> google.protobuf.Empty
	5,  // 20: nstance.v1.OperatorService.UpsertGroup:input_type -> nstance.v1.UpsertGroupRequest
	7,  // 21: nstance.v1.OperatorService.DeleteGroup:input_type -> nstance.v1.DeleteGroupRequest
	10, // 22: nstance.v1.OperatorService.CreateInstance:input_type -> nstance.v1.CreateInstanceRequest
	13, // 23: nstance.v1.OperatorService.DeleteInstance:input_type -> nstance.v1.DeleteInstanceRequest
	15, // 24: nstance.v1.OperatorService.GetInstanceStatus:input_type -> nstance.v1.GetInstanceStatusRequest
	19, // 25: nstance.v1.OperatorService.AcknowledgeDrained:input_type -> nstance.v1.DrainAckRequest
	26, // 26: nstance.v1.OperatorService.WatchGroups:input_type -> google.protobuf.Empty
	26, // 27: nstance.v1.OperatorService.WatchInstances:input_type -> google.protobuf.Empty
	26, // 28: nstance.v1.OperatorService.WatchErrors:input_type -> google.protobuf.Empty
	2,  // 29: nstance.v1.OperatorService.RenewCertificate:output_type -> nstance.v1.RenewCertificateResponse
	3,  // 30: nstance.v1.OperatorService.GetConfigStatus:output_type -> nstance.v1.ConfigStatusResponse
	4,  // 31: nstance.v1.OperatorService.RefreshConfig:output_type -> nstance.v1.RefreshConfigResponse
	8,  // 32: nstance.v1.OperatorService.ListGroups:output_type -> nstance.v1.ListGroupsResponse
	9,  // 33: nstance.v1.OperatorService.UpsertGroup:output_type -> nstance.v1.GroupStatus
	26, // 34: nstance.v1.OperatorService.DeleteGroup:output_type -> google.protobuf.Empty
	12, // 35: nstance.v1.OperatorService.CreateInstance:output_type -> nstance.v1.CreateInstanceResponse
	14, // 36: nstance.v1.OperatorService.DeleteInstance:output_type -> nstance.v1.DeleteInstanceResponse
	16, // 37: nstance.v1.OperatorService.GetInstanceStatus:output_type -> nstance.v1.InstanceStatusResponse
	26, // 38: nstance.v1.OperatorService.AcknowledgeDrained:output_type -> google.protobuf.Empty
	17, // 39: nstance.v1.OperatorService.WatchGroups:output_type -> nstance.v1.GroupEvent
	18, // 40: nstance.v1.OperatorService.WatchInstances:output_type -> nstance.v1.InstanceEvent
	20, // 41: nstance.v1.OperatorService.WatchErrors:output_type -> nstance.v1.ErrorEvent
	29, // [29:42] is the sub-list for method output_type
	16, // [16:29] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_proto_operator_proto_init() }
func file_proto_operator_proto_init() {
	if File_proto_operator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_operator_proto_rawDesc), len(file_proto_operator_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_operator_proto_goTypes,
		DependencyIndexes: file_proto_operator_proto_depIdxs,
		EnumInfos:         file_proto_operator_proto_enumTypes,
		MessageInfos:      file_proto_operator_proto_msgTypes,
	}.Build()
	File_proto_operator_proto = out.File
	file_proto_operator_proto_goTypes = nil
	file_proto_operator_proto_depIdxs = nil
}
