// Nstance <https://nstance.dev>
// Copyright The Nstance Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/operator.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OperatorService_RenewCertificate_FullMethodName   = "/nstance.v1.OperatorService/RenewCertificate"
	OperatorService_GetConfigStatus_FullMethodName    = "/nstance.v1.OperatorService/GetConfigStatus"
	OperatorService_RefreshConfig_FullMethodName      = "/nstance.v1.OperatorService/RefreshConfig"
	OperatorService_ListGroups_FullMethodName         = "/nstance.v1.OperatorService/ListGroups"
	OperatorService_UpsertGroup_FullMethodName        = "/nstance.v1.OperatorService/UpsertGroup"
	OperatorService_DeleteGroup_FullMethodName        = "/nstance.v1.OperatorService/DeleteGroup"
	OperatorService_CreateInstance_FullMethodName     = "/nstance.v1.OperatorService/CreateInstance"
	OperatorService_DeleteInstance_FullMethodName     = "/nstance.v1.OperatorService/DeleteInstance"
	OperatorService_GetInstanceStatus_FullMethodName  = "/nstance.v1.OperatorService/GetInstanceStatus"
	OperatorService_AcknowledgeDrained_FullMethodName = "/nstance.v1.OperatorService/AcknowledgeDrained"
	OperatorService_WatchGroups_FullMethodName        = "/nstance.v1.OperatorService/WatchGroups"
	OperatorService_WatchInstances_FullMethodName     = "/nstance.v1.OperatorService/WatchInstances"
	OperatorService_WatchErrors_FullMethodName        = "/nstance.v1.OperatorService/WatchErrors"
)

// OperatorServiceClient is the client API for OperatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// OperatorService provides authenticated API for Nstance Operator
type OperatorServiceClient interface {
	// Certificate renewal
	RenewCertificate(ctx context.Context, in *RenewCertificateRequest, opts ...grpc.CallOption) (*RenewCertificateResponse, error)
	// GetConfigStatus returns current configuration metadata for per-shard config
	GetConfigStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ConfigStatusResponse, error)
	// RefreshConfig triggers server to reload configuration from S3
	RefreshConfig(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RefreshConfigResponse, error)
	// Group management operations
	ListGroups(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListGroupsResponse, error)
	UpsertGroup(ctx context.Context, in *UpsertGroupRequest, opts ...grpc.CallOption) (*GroupStatus, error)
	DeleteGroup(ctx context.Context, in *DeleteGroupRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Instance management operations
	CreateInstance(ctx context.Context, in *CreateInstanceRequest, opts ...grpc.CallOption) (*CreateInstanceResponse, error)
	DeleteInstance(ctx context.Context, in *DeleteInstanceRequest, opts ...grpc.CallOption) (*DeleteInstanceResponse, error)
	GetInstanceStatus(ctx context.Context, in *GetInstanceStatusRequest, opts ...grpc.CallOption) (*InstanceStatusResponse, error)
	AcknowledgeDrained(ctx context.Context, in *DrainAckRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Watch streams for operator sync
	WatchGroups(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GroupEvent], error)
	WatchInstances(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[InstanceEvent], error)
	WatchErrors(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ErrorEvent], error)
}

type operatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOperatorServiceClient(cc grpc.ClientConnInterface) OperatorServiceClient {
	return &operatorServiceClient{cc}
}

func (c *operatorServiceClient) RenewCertificate(ctx context.Context, in *RenewCertificateRequest, opts ...grpc.CallOption) (*RenewCertificateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenewCertificateResponse)
	err := c.cc.Invoke(ctx, OperatorService_RenewCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorServiceClient) GetConfigStatus(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ConfigStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigStatusResponse)
	err := c.cc.Invoke(ctx, OperatorService_GetConfigStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorServiceClient) RefreshConfig(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*RefreshConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshConfigResponse)
	err := c.cc.Invoke(ctx, OperatorService_RefreshConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorServiceClient) ListGroups(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListGroupsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGroupsResponse)
	err := c.cc.Invoke(ctx, OperatorService_ListGroups_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorServiceClient) UpsertGroup(ctx context.Context, in *UpsertGroupRequest, opts ...grpc.CallOption) (*GroupStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupStatus)
	err := c.cc.Invoke(ctx, OperatorService_UpsertGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorServiceClient) DeleteGroup(ctx context.Context, in *DeleteGroupRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, OperatorService_DeleteGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorServiceClient) CreateInstance(ctx context.Context, in *CreateInstanceRequest, opts ...grpc.CallOption) (*CreateInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateInstanceResponse)
	err := c.cc.Invoke(ctx, OperatorService_CreateInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorServiceClient) DeleteInstance(ctx context.Context, in *DeleteInstanceRequest, opts ...grpc.CallOption) (*DeleteInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteInstanceResponse)
	err := c.cc.Invoke(ctx, OperatorService_DeleteInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorServiceClient) GetInstanceStatus(ctx context.Context, in *GetInstanceStatusRequest, opts ...grpc.CallOption) (*InstanceStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstanceStatusResponse)
	err := c.cc.Invoke(ctx, OperatorService_GetInstanceStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorServiceClient) AcknowledgeDrained(ctx context.Context, in *DrainAckRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, OperatorService_AcknowledgeDrained_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorServiceClient) WatchGroups(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GroupEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OperatorService_ServiceDesc.Streams[0], OperatorService_WatchGroups_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, GroupEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OperatorService_WatchGroupsClient = grpc.ServerStreamingClient[GroupEvent]

func (c *operatorServiceClient) WatchInstances(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[InstanceEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OperatorService_ServiceDesc.Streams[1], OperatorService_WatchInstances_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, InstanceEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OperatorService_WatchInstancesClient = grpc.ServerStreamingClient[InstanceEvent]

func (c *operatorServiceClient) WatchErrors(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ErrorEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OperatorService_ServiceDesc.Streams[2], OperatorService_WatchErrors_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, ErrorEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OperatorService_WatchErrorsClient = grpc.ServerStreamingClient[ErrorEvent]

// OperatorServiceServer is the server API for OperatorService service.
// All implementations must embed UnimplementedOperatorServiceServer
// for forward compatibility.
//
// OperatorService provides authenticated API for Nstance Operator
type OperatorServiceServer interface {
	// Certificate renewal
	RenewCertificate(context.Context, *RenewCertificateRequest) (*RenewCertificateResponse, error)
	// GetConfigStatus returns current configuration metadata for per-shard config
	GetConfigStatus(context.Context, *emptypb.Empty) (*ConfigStatusResponse, error)
	// RefreshConfig triggers server to reload configuration from S3
	RefreshConfig(context.Context, *emptypb.Empty) (*RefreshConfigResponse, error)
	// Group management operations
	ListGroups(context.Context, *emptypb.Empty) (*ListGroupsResponse, error)
	UpsertGroup(context.Context, *UpsertGroupRequest) (*GroupStatus, error)
	DeleteGroup(context.Context, *DeleteGroupRequest) (*emptypb.Empty, error)
	// Instance management operations
	CreateInstance(context.Context, *CreateInstanceRequest) (*CreateInstanceResponse, error)
	DeleteInstance(context.Context, *DeleteInstanceRequest) (*DeleteInstanceResponse, error)
	GetInstanceStatus(context.Context, *GetInstanceStatusRequest) (*InstanceStatusResponse, error)
	AcknowledgeDrained(context.Context, *DrainAckRequest) (*emptypb.Empty, error)
	// Watch streams for operator sync
	WatchGroups(*emptypb.Empty, grpc.ServerStreamingServer[GroupEvent]) error
	WatchInstances(*emptypb.Empty, grpc.ServerStreamingServer[InstanceEvent]) error
	WatchErrors(*emptypb.Empty, grpc.ServerStreamingServer[ErrorEvent]) error
	mustEmbedUnimplementedOperatorServiceServer()
}

// UnimplementedOperatorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOperatorServiceServer struct{}

func (UnimplementedOperatorServiceServer) RenewCertificate(context.Context, *RenewCertificateRequest) (*RenewCertificateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenewCertificate not implemented")
}
func (UnimplementedOperatorServiceServer) GetConfigStatus(context.Context, *emptypb.Empty) (*ConfigStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfigStatus not implemented")
}
func (UnimplementedOperatorServiceServer) RefreshConfig(context.Context, *emptypb.Empty) (*RefreshConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshConfig not implemented")
}
func (UnimplementedOperatorServiceServer) ListGroups(context.Context, *emptypb.Empty) (*ListGroupsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListGroups not implemented")
}
func (UnimplementedOperatorServiceServer) UpsertGroup(context.Context, *UpsertGroupRequest) (*GroupStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertGroup not implemented")
}
func (UnimplementedOperatorServiceServer) DeleteGroup(context.Context, *DeleteGroupRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGroup not implemented")
}
func (UnimplementedOperatorServiceServer) CreateInstance(context.Context, *CreateInstanceRequest) (*CreateInstanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateInstance not implemented")
}
func (UnimplementedOperatorServiceServer) DeleteInstance(context.Context, *DeleteInstanceRequest) (*DeleteInstanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteInstance not implemented")
}
func (UnimplementedOperatorServiceServer) GetInstanceStatus(context.Context, *GetInstanceStatusRequest) (*InstanceStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInstanceStatus not implemented")
}
func (UnimplementedOperatorServiceServer) AcknowledgeDrained(context.Context, *DrainAckRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcknowledgeDrained not implemented")
}
func (UnimplementedOperatorServiceServer) WatchGroups(*emptypb.Empty, grpc.ServerStreamingServer[GroupEvent]) error {
	return status.Errorf(codes.Unimplemented, "method WatchGroups not implemented")
}
func (UnimplementedOperatorServiceServer) WatchInstances(*emptypb.Empty, grpc.ServerStreamingServer[InstanceEvent]) error {
	return status.Errorf(codes.Unimplemented, "method WatchInstances not implemented")
}
func (UnimplementedOperatorServiceServer) WatchErrors(*emptypb.Empty, grpc.ServerStreamingServer[ErrorEvent]) error {
	return status.Errorf(codes.Unimplemented, "method WatchErrors not implemented")
}
func (UnimplementedOperatorServiceServer) mustEmbedUnimplementedOperatorServiceServer() {}
func (UnimplementedOperatorServiceServer) testEmbeddedByValue()                         {}

// UnsafeOperatorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OperatorServiceServer will
// result in compilation errors.
type UnsafeOperatorServiceServer interface {
	mustEmbedUnimplementedOperatorServiceServer()
}

func RegisterOperatorServiceServer(s grpc.ServiceRegistrar, srv OperatorServiceServer) {
	// If the following call pancis, it indicates UnimplementedOperatorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OperatorService_ServiceDesc, srv)
}

func _OperatorService_RenewCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServiceServer).RenewCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorService_RenewCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServiceServer).RenewCertificate(ctx, req.(*RenewCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorService_GetConfigStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServiceServer).GetConfigStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorService_GetConfigStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServiceServer).GetConfigStatus(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorService_RefreshConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServiceServer).RefreshConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorService_RefreshConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServiceServer).RefreshConfig(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorService_ListGroups_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServiceServer).ListGroups(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorService_ListGroups_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServiceServer).ListGroups(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorService_UpsertGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServiceServer).UpsertGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorService_UpsertGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServiceServer).UpsertGroup(ctx, req.(*UpsertGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorService_DeleteGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServiceServer).DeleteGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorService_DeleteGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServiceServer).DeleteGroup(ctx, req.(*DeleteGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorService_CreateInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServiceServer).CreateInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorService_CreateInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServiceServer).CreateInstance(ctx, req.(*CreateInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorService_DeleteInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServiceServer).DeleteInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorService_DeleteInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServiceServer).DeleteInstance(ctx, req.(*DeleteInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorService_GetInstanceStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstanceStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServiceServer).GetInstanceStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorService_GetInstanceStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServiceServer).GetInstanceStatus(ctx, req.(*GetInstanceStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorService_AcknowledgeDrained_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DrainAckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServiceServer).AcknowledgeDrained(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OperatorService_AcknowledgeDrained_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServiceServer).AcknowledgeDrained(ctx, req.(*DrainAckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OperatorService_WatchGroups_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OperatorServiceServer).WatchGroups(m, &grpc.GenericServerStream[emptypb.Empty, GroupEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OperatorService_WatchGroupsServer = grpc.ServerStreamingServer[GroupEvent]

func _OperatorService_WatchInstances_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OperatorServiceServer).WatchInstances(m, &grpc.GenericServerStream[emptypb.Empty, InstanceEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OperatorService_WatchInstancesServer = grpc.ServerStreamingServer[InstanceEvent]

func _OperatorService_WatchErrors_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OperatorServiceServer).WatchErrors(m, &grpc.GenericServerStream[emptypb.Empty, ErrorEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OperatorService_WatchErrorsServer = grpc.ServerStreamingServer[ErrorEvent]

// OperatorService_ServiceDesc is the grpc.ServiceDesc for OperatorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OperatorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nstance.v1.OperatorService",
	HandlerType: (*OperatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RenewCertificate",
			Handler:    _OperatorService_RenewCertificate_Handler,
		},
		{
			MethodName: "GetConfigStatus",
			Handler:    _OperatorService_GetConfigStatus_Handler,
		},
		{
			MethodName: "RefreshConfig",
			Handler:    _OperatorService_RefreshConfig_Handler,
		},
		{
			MethodName: "ListGroups",
			Handler:    _OperatorService_ListGroups_Handler,
		},
		{
			MethodName: "UpsertGroup",
			Handler:    _OperatorService_UpsertGroup_Handler,
		},
		{
			MethodName: "DeleteGroup",
			Handler:    _OperatorService_DeleteGroup_Handler,
		},
		{
			MethodName: "CreateInstance",
			Handler:    _OperatorService_CreateInstance_Handler,
		},
		{
			MethodName: "DeleteInstance",
			Handler:    _OperatorService_DeleteInstance_Handler,
		},
		{
			MethodName: "GetInstanceStatus",
			Handler:    _OperatorService_GetInstanceStatus_Handler,
		},
		{
			MethodName: "AcknowledgeDrained",
			Handler:    _OperatorService_AcknowledgeDrained_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchGroups",
			Handler:       _OperatorService_WatchGroups_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchInstances",
			Handler:       _OperatorService_WatchInstances_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchErrors",
			Handler:       _OperatorService_WatchErrors_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/operator.proto",
}
