// Nstance <https://nstance.dev>
// Copyright The Nstance Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/proxy.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WatchProxyConfigRequest starts a complete proxy configuration watch.
type WatchProxyConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchProxyConfigRequest) Reset() {
	*x = WatchProxyConfigRequest{}
	mi := &file_proto_proxy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchProxyConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchProxyConfigRequest) ProtoMessage() {}

func (x *WatchProxyConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proxy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchProxyConfigRequest.ProtoReflect.Descriptor instead.
func (*WatchProxyConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_proxy_proto_rawDescGZIP(), []int{0}
}

// ProxyWakeRequest identifies the local listener that received traffic.
type ProxyWakeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Listener      string                 `protobuf:"bytes,1,opt,name=listener,proto3" json:"listener,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyWakeRequest) Reset() {
	*x = ProxyWakeRequest{}
	mi := &file_proto_proxy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyWakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyWakeRequest) ProtoMessage() {}

func (x *ProxyWakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proxy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyWakeRequest.ProtoReflect.Descriptor instead.
func (*ProxyWakeRequest) Descriptor() ([]byte, []int) {
	return file_proto_proxy_proto_rawDescGZIP(), []int{1}
}

func (x *ProxyWakeRequest) GetListener() string {
	if x != nil {
		return x.Listener
	}
	return ""
}

// ProxyConfigSnapshot replaces the proxy's complete listener configuration.
type ProxyConfigSnapshot struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Generation    uint64                    `protobuf:"varint,1,opt,name=generation,proto3" json:"generation,omitempty"`
	Listeners     map[string]*ProxyListener `protobuf:"bytes,2,rep,name=listeners,proto3" json:"listeners,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyConfigSnapshot) Reset() {
	*x = ProxyConfigSnapshot{}
	mi := &file_proto_proxy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyConfigSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyConfigSnapshot) ProtoMessage() {}

func (x *ProxyConfigSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proxy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyConfigSnapshot.ProtoReflect.Descriptor instead.
func (*ProxyConfigSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_proxy_proto_rawDescGZIP(), []int{2}
}

func (x *ProxyConfigSnapshot) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *ProxyConfigSnapshot) GetListeners() map[string]*ProxyListener {
	if x != nil {
		return x.Listeners
	}
	return nil
}

// ProxyListener describes one listener route delivered to the local proxy.
type ProxyListener struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        string                 `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Groups        []string               `protobuf:"bytes,2,rep,name=groups,proto3" json:"groups,omitempty"`
	TargetPort    uint32                 `protobuf:"varint,3,opt,name=target_port,json=targetPort,proto3" json:"target_port,omitempty"`
	ProxyPort     uint32                 `protobuf:"varint,4,opt,name=proxy_port,json=proxyPort,proto3" json:"proxy_port,omitempty"`
	DestinationIp *string                `protobuf:"bytes,5,opt,name=destination_ip,json=destinationIp,proto3,oneof" json:"destination_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyListener) Reset() {
	*x = ProxyListener{}
	mi := &file_proto_proxy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyListener) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyListener) ProtoMessage() {}

func (x *ProxyListener) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proxy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyListener.ProtoReflect.Descriptor instead.
func (*ProxyListener) Descriptor() ([]byte, []int) {
	return file_proto_proxy_proto_rawDescGZIP(), []int{3}
}

func (x *ProxyListener) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *ProxyListener) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *ProxyListener) GetTargetPort() uint32 {
	if x != nil {
		return x.TargetPort
	}
	return 0
}

func (x *ProxyListener) GetProxyPort() uint32 {
	if x != nil {
		return x.ProxyPort
	}
	return 0
}

func (x *ProxyListener) GetDestinationIp() string {
	if x != nil && x.DestinationIp != nil {
		return *x.DestinationIp
	}
	return ""
}

var File_proto_proxy_proto protoreflect.FileDescriptor

const file_proto_proxy_proto_rawDesc = "" +
	"\n" +
	"\x11proto/proxy.proto\x12\n" +
	"nstance.v1\x1a\x14proto/operator.proto\"\x19\n" +
	"\x17WatchProxyConfigRequest\".\n" +
	"\x10ProxyWakeRequest\x12\x1a\n" +
	"\blistener\x18\x01 \x01(\tR\blistener\"\xdc\x01\n" +
	"\x13ProxyConfigSnapshot\x12\x1e\n" +
	"\n" +
	"generation\x18\x01 \x01(\x04R\n" +
	"generation\x12L\n" +
	"\tlisteners\x18\x02 \x03(\v2..nstance.v1.ProxyConfigSnapshot.ListenersEntryR\tlisteners\x1aW\n" +
	"\x0eListenersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12/\n" +
	"\x05value\x18\x02 \x01(\v2\x19.nstance.v1.ProxyListenerR\x05value:\x028\x01\"\xbe\x01\n" +
	"\rProxyListener\x12\x16\n" +
	"\x06tenant\x18\x01 \x01(\tR\x06tenant\x12\x16\n" +
	"\x06groups\x18\x02 \x03(\tR\x06groups\x12\x1f\n" +
	"\vtarget_port\x18\x03 \x01(\rR\n" +
	"targetPort\x12\x1d\n" +
	"\n" +
	"proxy_port\x18\x04 \x01(\rR\tproxyPort\x12*\n" +
	"\x0edestination_ip\x18\x05 \x01(\tH\x00R\rdestinationIp\x88\x01\x01B\x11\n" +
	"\x0f_destination_ip2\xb1\x01\n" +
	"\fProxyService\x12U\n" +
	"\vWatchConfig\x12#.nstance.v1.WatchProxyConfigRequest\x1a\x1f.nstance.v1.ProxyConfigSnapshot0\x01\x12J\n" +
	"\n" +
	"WakeTenant\x12\x1c.nstance.v1.ProxyWakeRequest\x1a\x1e.nstance.v1.WakeTenantResponseB/Z-github.com/nstance-dev/nstance/internal/protob\x06proto3"

var (
	file_proto_proxy_proto_rawDescOnce sync.Once
	file_proto_proxy_proto_rawDescData []byte
)

func file_proto_proxy_proto_rawDescGZIP() []byte {
	file_proto_proxy_proto_rawDescOnce.Do(func() {
		file_proto_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_proxy_proto_rawDesc), len(file_proto_proxy_proto_rawDesc)))
	})
	return file_proto_proxy_proto_rawDescData
}

var file_proto_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_proxy_proto_goTypes = []any{
	(*WatchProxyConfigRequest)(nil), // 0: nstance.v1.WatchProxyConfigRequest
	(*ProxyWakeRequest)(nil),        // 1: nstance.v1.ProxyWakeRequest
	(*ProxyConfigSnapshot)(nil),     // 2: nstance.v1.ProxyConfigSnapshot
	(*ProxyListener)(nil),           // 3: nstance.v1.ProxyListener
	nil,                             // 4: nstance.v1.ProxyConfigSnapshot.ListenersEntry
	(*WakeTenantResponse)(nil),      // 5: nstance.v1.WakeTenantResponse
}
var file_proto_proxy_proto_depIdxs = []int32{
	4, // 0: nstance.v1.ProxyConfigSnapshot.listeners:type_name -> nstance.v1.ProxyConfigSnapshot.ListenersEntry
	3, // 1: nstance.v1.ProxyConfigSnapshot.ListenersEntry.value:type_name -> nstance.v1.ProxyListener
	0, // 2: nstance.v1.ProxyService.WatchConfig:input_type -> nstance.v1.WatchProxyConfigRequest
	1, // 3: nstance.v1.ProxyService.WakeTenant:input_type -> nstance.v1.ProxyWakeRequest
	2, // 4: nstance.v1.ProxyService.WatchConfig:output_type -> nstance.v1.ProxyConfigSnapshot
	5, // 5: nstance.v1.ProxyService.WakeTenant:output_type -> nstance.v1.WakeTenantResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_proxy_proto_init() }
func file_proto_proxy_proto_init() {
	if File_proto_proxy_proto != nil {
		return
	}
	file_proto_operator_proto_init()
	file_proto_proxy_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_proxy_proto_rawDesc), len(file_proto_proxy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_proxy_proto_goTypes,
		DependencyIndexes: file_proto_proxy_proto_depIdxs,
		MessageInfos:      file_proto_proxy_proto_msgTypes,
	}.Build()
	File_proto_proxy_proto = out.File
	file_proto_proxy_proto_goTypes = nil
	file_proto_proxy_proto_depIdxs = nil
}
