// Nstance <https://nstance.dev>
// Copyright The Nstance Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: proto/proxy.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProxyService_WatchConfig_FullMethodName = "/nstance.v1.ProxyService/WatchConfig"
	ProxyService_WakeTenant_FullMethodName  = "/nstance.v1.ProxyService/WakeTenant"
)

// ProxyServiceClient is the client API for ProxyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ProxyService is the complete local API available to nstance-proxy.
type ProxyServiceClient interface {
	WatchConfig(ctx context.Context, in *WatchProxyConfigRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProxyConfigSnapshot], error)
	WakeTenant(ctx context.Context, in *ProxyWakeRequest, opts ...grpc.CallOption) (*WakeTenantResponse, error)
}

type proxyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProxyServiceClient(cc grpc.ClientConnInterface) ProxyServiceClient {
	return &proxyServiceClient{cc}
}

func (c *proxyServiceClient) WatchConfig(ctx context.Context, in *WatchProxyConfigRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProxyConfigSnapshot], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ProxyService_ServiceDesc.Streams[0], ProxyService_WatchConfig_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchProxyConfigRequest, ProxyConfigSnapshot]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProxyService_WatchConfigClient = grpc.ServerStreamingClient[ProxyConfigSnapshot]

func (c *proxyServiceClient) WakeTenant(ctx context.Context, in *ProxyWakeRequest, opts ...grpc.CallOption) (*WakeTenantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WakeTenantResponse)
	err := c.cc.Invoke(ctx, ProxyService_WakeTenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProxyServiceServer is the server API for ProxyService service.
// All implementations must embed UnimplementedProxyServiceServer
// for forward compatibility.
//
// ProxyService is the complete local API available to nstance-proxy.
type ProxyServiceServer interface {
	WatchConfig(*WatchProxyConfigRequest, grpc.ServerStreamingServer[ProxyConfigSnapshot]) error
	WakeTenant(context.Context, *ProxyWakeRequest) (*WakeTenantResponse, error)
	mustEmbedUnimplementedProxyServiceServer()
}

// UnimplementedProxyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProxyServiceServer struct{}

func (UnimplementedProxyServiceServer) WatchConfig(*WatchProxyConfigRequest, grpc.ServerStreamingServer[ProxyConfigSnapshot]) error {
	return status.Error(codes.Unimplemented, "method WatchConfig not implemented")
}
func (UnimplementedProxyServiceServer) WakeTenant(context.Context, *ProxyWakeRequest) (*WakeTenantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WakeTenant not implemented")
}
func (UnimplementedProxyServiceServer) mustEmbedUnimplementedProxyServiceServer() {}
func (UnimplementedProxyServiceServer) testEmbeddedByValue()                      {}

// UnsafeProxyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProxyServiceServer will
// result in compilation errors.
type UnsafeProxyServiceServer interface {
	mustEmbedUnimplementedProxyServiceServer()
}

func RegisterProxyServiceServer(s grpc.ServiceRegistrar, srv ProxyServiceServer) {
	// If the following call panics, it indicates UnimplementedProxyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProxyService_ServiceDesc, srv)
}

func _ProxyService_WatchConfig_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchProxyConfigRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProxyServiceServer).WatchConfig(m, &grpc.GenericServerStream[WatchProxyConfigRequest, ProxyConfigSnapshot]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ProxyService_WatchConfigServer = grpc.ServerStreamingServer[ProxyConfigSnapshot]

func _ProxyService_WakeTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProxyWakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProxyServiceServer).WakeTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProxyService_WakeTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProxyServiceServer).WakeTenant(ctx, req.(*ProxyWakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProxyService_ServiceDesc is the grpc.ServiceDesc for ProxyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProxyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nstance.v1.ProxyService",
	HandlerType: (*ProxyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WakeTenant",
			Handler:    _ProxyService_WakeTenant_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchConfig",
			Handler:       _ProxyService_WatchConfig_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/proxy.proto",
}
