// Nstance <https://nstance.dev>
// Copyright 2026 Nadrama Pty Ltd
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: proto/registration.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterClientRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	RegistrationNonceJwt string                 `protobuf:"bytes,1,opt,name=registration_nonce_jwt,json=registrationNonceJwt,proto3" json:"registration_nonce_jwt,omitempty"`
	PublicKeyPem         []byte                 `protobuf:"bytes,2,opt,name=public_key_pem,json=publicKeyPem,proto3" json:"public_key_pem,omitempty"` // PEM-encoded public key
	PrivateIpv4          string                 `protobuf:"bytes,3,opt,name=private_ipv4,json=privateIpv4,proto3" json:"private_ipv4,omitempty"`      // Agent-reported private IPv4
	PrivateIpv6          string                 `protobuf:"bytes,4,opt,name=private_ipv6,json=privateIpv6,proto3" json:"private_ipv6,omitempty"`      // Agent-reported private IPv6
	Hostname             string                 `protobuf:"bytes,5,opt,name=hostname,proto3" json:"hostname,omitempty"`                               // Agent-reported hostname
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RegisterClientRequest) Reset() {
	*x = RegisterClientRequest{}
	mi := &file_proto_registration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterClientRequest) ProtoMessage() {}

func (x *RegisterClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_registration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterClientRequest.ProtoReflect.Descriptor instead.
func (*RegisterClientRequest) Descriptor() ([]byte, []int) {
	return file_proto_registration_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterClientRequest) GetRegistrationNonceJwt() string {
	if x != nil {
		return x.RegistrationNonceJwt
	}
	return ""
}

func (x *RegisterClientRequest) GetPublicKeyPem() []byte {
	if x != nil {
		return x.PublicKeyPem
	}
	return nil
}

func (x *RegisterClientRequest) GetPrivateIpv4() string {
	if x != nil {
		return x.PrivateIpv4
	}
	return ""
}

func (x *RegisterClientRequest) GetPrivateIpv6() string {
	if x != nil {
		return x.PrivateIpv6
	}
	return ""
}

func (x *RegisterClientRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type RegisterClientResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ClientCertificatePem []byte                 `protobuf:"bytes,1,opt,name=client_certificate_pem,json=clientCertificatePem,proto3" json:"client_certificate_pem,omitempty"` // PEM-encoded client certificate
	ExpiresAt            *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RegisterClientResponse) Reset() {
	*x = RegisterClientResponse{}
	mi := &file_proto_registration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterClientResponse) ProtoMessage() {}

func (x *RegisterClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_registration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterClientResponse.ProtoReflect.Descriptor instead.
func (*RegisterClientResponse) Descriptor() ([]byte, []int) {
	return file_proto_registration_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterClientResponse) GetClientCertificatePem() []byte {
	if x != nil {
		return x.ClientCertificatePem
	}
	return nil
}

func (x *RegisterClientResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

var File_proto_registration_proto protoreflect.FileDescriptor

const file_proto_registration_proto_rawDesc = "" +
	"\n" +
	"\x18proto/registration.proto\x12\n" +
	"nstance.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd5\x01\n" +
	"\x15RegisterClientRequest\x124\n" +
	"\x16registration_nonce_jwt\x18\x01 \x01(\tR\x14registrationNonceJwt\x12$\n" +
	"\x0epublic_key_pem\x18\x02 \x01(\fR\fpublicKeyPem\x12!\n" +
	"\fprivate_ipv4\x18\x03 \x01(\tR\vprivateIpv4\x12!\n" +
	"\fprivate_ipv6\x18\x04 \x01(\tR\vprivateIpv6\x12\x1a\n" +
	"\bhostname\x18\x05 \x01(\tR\bhostname\"\x89\x01\n" +
	"\x16RegisterClientResponse\x124\n" +
	"\x16client_certificate_pem\x18\x01 \x01(\fR\x14clientCertificatePem\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt2\xc8\x01\n" +
	"\x13RegistrationService\x12V\n" +
	"\rRegisterAgent\x12!.nstance.v1.RegisterClientRequest\x1a\".nstance.v1.RegisterClientResponse\x12Y\n" +
	"\x10RegisterOperator\x12!.nstance.v1.RegisterClientRequest\x1a\".nstance.v1.RegisterClientResponseB/Z-github.com/nstance-dev/nstance/internal/protob\x06proto3"

var (
	file_proto_registration_proto_rawDescOnce sync.Once
	file_proto_registration_proto_rawDescData []byte
)

func file_proto_registration_proto_rawDescGZIP() []byte {
	file_proto_registration_proto_rawDescOnce.Do(func() {
		file_proto_registration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_registration_proto_rawDesc), len(file_proto_registration_proto_rawDesc)))
	})
	return file_proto_registration_proto_rawDescData
}

var file_proto_registration_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_registration_proto_goTypes = []any{
	(*RegisterClientRequest)(nil),  // 0: nstance.v1.RegisterClientRequest
	(*RegisterClientResponse)(nil), // 1: nstance.v1.RegisterClientResponse
	(*timestamppb.Timestamp)(nil),  // 2: google.protobuf.Timestamp
}
var file_proto_registration_proto_depIdxs = []int32{
	2, // 0: nstance.v1.RegisterClientResponse.expires_at:type_name -> google.protobuf.Timestamp
	0, // 1: nstance.v1.RegistrationService.RegisterAgent:input_type -> nstance.v1.RegisterClientRequest
	0, // 2: nstance.v1.RegistrationService.RegisterOperator:input_type -> nstance.v1.RegisterClientRequest
	1, // 3: nstance.v1.RegistrationService.RegisterAgent:output_type -> nstance.v1.RegisterClientResponse
	1, // 4: nstance.v1.RegistrationService.RegisterOperator:output_type -> nstance.v1.RegisterClientResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_registration_proto_init() }
func file_proto_registration_proto_init() {
	if File_proto_registration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_registration_proto_rawDesc), len(file_proto_registration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_registration_proto_goTypes,
		DependencyIndexes: file_proto_registration_proto_depIdxs,
		MessageInfos:      file_proto_registration_proto_msgTypes,
	}.Build()
	File_proto_registration_proto = out.File
	file_proto_registration_proto_goTypes = nil
	file_proto_registration_proto_depIdxs = nil
}
