// Nstance <https://nstance.dev>
// Copyright The Nstance Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/tunnel.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// State is the requested tunnel lifecycle state.
type TunnelDesiredState_State int32

const (
	TunnelDesiredState_TUNNEL_DESIRED_STATE_UNSPECIFIED TunnelDesiredState_State = 0
	TunnelDesiredState_TUNNEL_DESIRED_STATE_RUNNING     TunnelDesiredState_State = 1
	TunnelDesiredState_TUNNEL_DESIRED_STATE_STOPPED     TunnelDesiredState_State = 2
)

// Enum value maps for TunnelDesiredState_State.
var (
	TunnelDesiredState_State_name = map[int32]string{
		0: "TUNNEL_DESIRED_STATE_UNSPECIFIED",
		1: "TUNNEL_DESIRED_STATE_RUNNING",
		2: "TUNNEL_DESIRED_STATE_STOPPED",
	}
	TunnelDesiredState_State_value = map[string]int32{
		"TUNNEL_DESIRED_STATE_UNSPECIFIED": 0,
		"TUNNEL_DESIRED_STATE_RUNNING":     1,
		"TUNNEL_DESIRED_STATE_STOPPED":     2,
	}
)

func (x TunnelDesiredState_State) Enum() *TunnelDesiredState_State {
	p := new(TunnelDesiredState_State)
	*p = x
	return p
}

func (x TunnelDesiredState_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TunnelDesiredState_State) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_tunnel_proto_enumTypes[0].Descriptor()
}

func (TunnelDesiredState_State) Type() protoreflect.EnumType {
	return &file_proto_tunnel_proto_enumTypes[0]
}

func (x TunnelDesiredState_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TunnelDesiredState_State.Descriptor instead.
func (TunnelDesiredState_State) EnumDescriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{0, 0}
}

// State is the observed tunnel lifecycle state.
type TunnelStatus_State int32

const (
	TunnelStatus_TUNNEL_STATUS_STATE_UNSPECIFIED TunnelStatus_State = 0
	TunnelStatus_TUNNEL_STATUS_STATE_STARTING    TunnelStatus_State = 1
	TunnelStatus_TUNNEL_STATUS_STATE_READY       TunnelStatus_State = 2
	TunnelStatus_TUNNEL_STATUS_STATE_FAILED      TunnelStatus_State = 3
	TunnelStatus_TUNNEL_STATUS_STATE_STOPPED     TunnelStatus_State = 4
)

// Enum value maps for TunnelStatus_State.
var (
	TunnelStatus_State_name = map[int32]string{
		0: "TUNNEL_STATUS_STATE_UNSPECIFIED",
		1: "TUNNEL_STATUS_STATE_STARTING",
		2: "TUNNEL_STATUS_STATE_READY",
		3: "TUNNEL_STATUS_STATE_FAILED",
		4: "TUNNEL_STATUS_STATE_STOPPED",
	}
	TunnelStatus_State_value = map[string]int32{
		"TUNNEL_STATUS_STATE_UNSPECIFIED": 0,
		"TUNNEL_STATUS_STATE_STARTING":    1,
		"TUNNEL_STATUS_STATE_READY":       2,
		"TUNNEL_STATUS_STATE_FAILED":      3,
		"TUNNEL_STATUS_STATE_STOPPED":     4,
	}
)

func (x TunnelStatus_State) Enum() *TunnelStatus_State {
	p := new(TunnelStatus_State)
	*p = x
	return p
}

func (x TunnelStatus_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TunnelStatus_State) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_tunnel_proto_enumTypes[1].Descriptor()
}

func (TunnelStatus_State) Type() protoreflect.EnumType {
	return &file_proto_tunnel_proto_enumTypes[1]
}

func (x TunnelStatus_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TunnelStatus_State.Descriptor instead.
func (TunnelStatus_State) EnumDescriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{1, 0}
}

// TunnelDesiredState requests a revisioned lifecycle state for one tunnel.
type TunnelDesiredState struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	TunnelName    string                   `protobuf:"bytes,1,opt,name=tunnel_name,json=tunnelName,proto3" json:"tunnel_name,omitempty"`
	Revision      uint64                   `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	State         TunnelDesiredState_State `protobuf:"varint,3,opt,name=state,proto3,enum=nstance.v1.TunnelDesiredState_State" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelDesiredState) Reset() {
	*x = TunnelDesiredState{}
	mi := &file_proto_tunnel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelDesiredState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelDesiredState) ProtoMessage() {}

func (x *TunnelDesiredState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelDesiredState.ProtoReflect.Descriptor instead.
func (*TunnelDesiredState) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{0}
}

func (x *TunnelDesiredState) GetTunnelName() string {
	if x != nil {
		return x.TunnelName
	}
	return ""
}

func (x *TunnelDesiredState) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *TunnelDesiredState) GetState() TunnelDesiredState_State {
	if x != nil {
		return x.State
	}
	return TunnelDesiredState_TUNNEL_DESIRED_STATE_UNSPECIFIED
}

// TunnelStatus reports a revisioned tunnel lifecycle observation.
type TunnelStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TunnelName    string                 `protobuf:"bytes,1,opt,name=tunnel_name,json=tunnelName,proto3" json:"tunnel_name,omitempty"`
	Revision      uint64                 `protobuf:"varint,2,opt,name=revision,proto3" json:"revision,omitempty"`
	State         TunnelStatus_State     `protobuf:"varint,3,opt,name=state,proto3,enum=nstance.v1.TunnelStatus_State" json:"state,omitempty"`
	Error         *string                `protobuf:"bytes,4,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TunnelStatus) Reset() {
	*x = TunnelStatus{}
	mi := &file_proto_tunnel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TunnelStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TunnelStatus) ProtoMessage() {}

func (x *TunnelStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tunnel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TunnelStatus.ProtoReflect.Descriptor instead.
func (*TunnelStatus) Descriptor() ([]byte, []int) {
	return file_proto_tunnel_proto_rawDescGZIP(), []int{1}
}

func (x *TunnelStatus) GetTunnelName() string {
	if x != nil {
		return x.TunnelName
	}
	return ""
}

func (x *TunnelStatus) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

func (x *TunnelStatus) GetState() TunnelStatus_State {
	if x != nil {
		return x.State
	}
	return TunnelStatus_TUNNEL_STATUS_STATE_UNSPECIFIED
}

func (x *TunnelStatus) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

var File_proto_tunnel_proto protoreflect.FileDescriptor

const file_proto_tunnel_proto_rawDesc = "" +
	"\n" +
	"\x12proto/tunnel.proto\x12\n" +
	"nstance.v1\"\x80\x02\n" +
	"\x12TunnelDesiredState\x12\x1f\n" +
	"\vtunnel_name\x18\x01 \x01(\tR\n" +
	"tunnelName\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x04R\brevision\x12:\n" +
	"\x05state\x18\x03 \x01(\x0e2$.nstance.v1.TunnelDesiredState.StateR\x05state\"q\n" +
	"\x05State\x12$\n" +
	" TUNNEL_DESIRED_STATE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cTUNNEL_DESIRED_STATE_RUNNING\x10\x01\x12 \n" +
	"\x1cTUNNEL_DESIRED_STATE_STOPPED\x10\x02\"\xd7\x02\n" +
	"\fTunnelStatus\x12\x1f\n" +
	"\vtunnel_name\x18\x01 \x01(\tR\n" +
	"tunnelName\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\x04R\brevision\x124\n" +
	"\x05state\x18\x03 \x01(\x0e2\x1e.nstance.v1.TunnelStatus.StateR\x05state\x12\x19\n" +
	"\x05error\x18\x04 \x01(\tH\x00R\x05error\x88\x01\x01\"\xae\x01\n" +
	"\x05State\x12#\n" +
	"\x1fTUNNEL_STATUS_STATE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cTUNNEL_STATUS_STATE_STARTING\x10\x01\x12\x1d\n" +
	"\x19TUNNEL_STATUS_STATE_READY\x10\x02\x12\x1e\n" +
	"\x1aTUNNEL_STATUS_STATE_FAILED\x10\x03\x12\x1f\n" +
	"\x1bTUNNEL_STATUS_STATE_STOPPED\x10\x04B\b\n" +
	"\x06_error2W\n" +
	"\rTunnelService\x12F\n" +
	"\x06Manage\x12\x1e.nstance.v1.TunnelDesiredState\x1a\x18.nstance.v1.TunnelStatus(\x010\x01B/Z-github.com/nstance-dev/nstance/internal/protob\x06proto3"

var (
	file_proto_tunnel_proto_rawDescOnce sync.Once
	file_proto_tunnel_proto_rawDescData []byte
)

func file_proto_tunnel_proto_rawDescGZIP() []byte {
	file_proto_tunnel_proto_rawDescOnce.Do(func() {
		file_proto_tunnel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tunnel_proto_rawDesc), len(file_proto_tunnel_proto_rawDesc)))
	})
	return file_proto_tunnel_proto_rawDescData
}

var file_proto_tunnel_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_tunnel_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_tunnel_proto_goTypes = []any{
	(TunnelDesiredState_State)(0), // 0: nstance.v1.TunnelDesiredState.State
	(TunnelStatus_State)(0),       // 1: nstance.v1.TunnelStatus.State
	(*TunnelDesiredState)(nil),    // 2: nstance.v1.TunnelDesiredState
	(*TunnelStatus)(nil),          // 3: nstance.v1.TunnelStatus
}
var file_proto_tunnel_proto_depIdxs = []int32{
	0, // 0: nstance.v1.TunnelDesiredState.state:type_name -> nstance.v1.TunnelDesiredState.State
	1, // 1: nstance.v1.TunnelStatus.state:type_name -> nstance.v1.TunnelStatus.State
	2, // 2: nstance.v1.TunnelService.Manage:input_type -> nstance.v1.TunnelDesiredState
	3, // 3: nstance.v1.TunnelService.Manage:output_type -> nstance.v1.TunnelStatus
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_tunnel_proto_init() }
func file_proto_tunnel_proto_init() {
	if File_proto_tunnel_proto != nil {
		return
	}
	file_proto_tunnel_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tunnel_proto_rawDesc), len(file_proto_tunnel_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tunnel_proto_goTypes,
		DependencyIndexes: file_proto_tunnel_proto_depIdxs,
		EnumInfos:         file_proto_tunnel_proto_enumTypes,
		MessageInfos:      file_proto_tunnel_proto_msgTypes,
	}.Build()
	File_proto_tunnel_proto = out.File
	file_proto_tunnel_proto_goTypes = nil
	file_proto_tunnel_proto_depIdxs = nil
}
