# Nstance <https://nstance.dev>
# Copyright 2026 Nadrama Pty Ltd
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nstance-capi-workload
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "nstance-operator.labels" . | nindent 4 }}
{{- end }}
