# Nstance <https://nstance.dev>
# Copyright 2026 Nadrama Pty Ltd
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.installCRDs }}
---
{{ .Files.Get "crds/nstanceclusters.infrastructure.cluster.x-k8s.io.yaml" }}
---
{{ .Files.Get "crds/nstancemachinepools.infrastructure.cluster.x-k8s.io.yaml" }}
---
{{ .Files.Get "crds/nstancemachines.infrastructure.cluster.x-k8s.io.yaml" }}
---
{{ .Files.Get "crds/nstancemachinetemplates.infrastructure.cluster.x-k8s.io.yaml" }}
---
{{ .Files.Get "crds/nstanceshardgroups.infrastructure.cluster.x-k8s.io.yaml" }}
{{- end }}
