#!/usr/bin/env bash
# Nstance <https://nstance.dev>
# Copyright The Nstance Authors
# SPDX-License-Identifier: Apache-2.0
set -eo pipefail

echo "Running pre-commit checks..."
make precommit
echo "Pre-commit checks passed!"
